### ISSUE TITLE
UnicodeDecodeError when running buildout

### ISSUE THREAD

**Issue by hvelarde** [buildout/buildout#148]
if you have a package that contains a directory with a name encoded, you will see the following error when running buildout:

```python
(python-2.7)# hvelarde@nanovac (jenkins-csslint) ~/plone/recipe.codeanalysis 
# bin/buildout -D
Develop: '/home/hvelarde/plone/recipe.codeanalysis/.'
While:
  Installing.
Traceback (most recent call last):
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1942, in main
    getattr(buildout, command)(args)
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 521, in install
    self._compute_part_signatures(install_parts)
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 766, in _compute_part_signatures
    sig = _dists_sig(pkg_resources.working_set.resolve([req]))
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1633, in _dists_sig
    result.append(dist.project_name + '-' + _dir_hash(location))
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1601, in _dir_hash
    hash.update(' '.join(dirnames).encode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 21: ordinal not in range(128)

Starting pdb:
> /home/hvelarde/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py(1601)_dir_hash()
-> hash.update(' '.join(dirnames).encode())
(Pdb) l
1596 	        dirnames[:] = sorted(n for n in dirnames if n not in ignore_directories)
1597 	        filenames[:] = sorted(f for f in filenames
1598 	                              if (not (f.endswith('pyc') or f.endswith('pyo'))
1599 	                                  and os.path.exists(os.path.join(dirpath, f)))
1600 	                              )
1601 ->	        hash.update(' '.join(dirnames).encode())
1602 	        hash.update(' '.join(filenames).encode())
1603 	        for name in filenames:
1604 	            path = os.path.join(dirpath, name)
1605 	            if name == 'entry_points.txt':
1606 	                f = open(path)
(Pdb) dirnames
['empty', 'empty2', 'encoding\xc4\x8d', 'missing_namespace_key', 'multiconfig', 'questions1', 'questions2', 'questions3', 'questions4', 'questions5', 'renamed', 'renamedfile', 'renamedir', 'renamedtemplate', 'renamedtemplate2', 'render_hooks', 'renderer', 'skip_mrbobini', 'unbound']
(Pdb) dirpath
'/home/hvelarde/buildout.python/python-2.7/lib/python2.7/site-packages/mrbob/tests/templates'
(Pdb) 
```

**Comment by vangheem** [comment]
I'm also getting this and can not figure out a way around it right now except for patching(or downgrading to an 1.4 version of zc.buildout)

to fix, change:
```
hash.update(' '.join(dirnames).encode())
hash.update(' '.join(filenames).encode())
```

to something like:

```
try:
    hash.update(' '.join(dirnames).encode())
except UnicodeDecodeError:
    hash.update(' '.join(dirnames))
try:
    hash.update(' '.join(filenames).encode())
except UnicodeDecodeError:
    hash.update(' '.join(filenames))
```

**Comment by idgserpro** [comment]
Any news about this error and possible solutions? This bug is really confusing for newbies.

**Comment by reinout** [comment]
Perhaps useful: recently zest.releaser got python 3 support. There is a method in there that tries to return proper unicode filenames whatever you feed it:

    def fs_to_text(fs_name):
        if not isinstance(fs_name, six.text_type):
            fs_name = fs_name.decode(sys.getfilesystemencoding(),
                                     'surrogateescape')
        return fs_name

See https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/utils.py#L45

**Comment by reinout** [comment]
Pull request #250 fixes this. Can someone take a look?

**Comment by reinout** [comment]
Buildout 2.4.0 fixes it.

**Comment by hvelarde** [comment]
asesome! thanks!
