### ISSUE TITLE
Setting directory in buildout section causes incorrect path expansion of standard directories.

### ISSUE THREAD

**Issue by hashstat** [buildout/buildout#173]
This buildout.cfg

```
[buildout]
directory = buildout
develop = .
```

results in a `FileNotFoundError:  [Errno 2] No such file or directory: 'buildout/buildout/bin'` exception. As can be seen in the output, the directory in question is _buildout/buildout/bin_ rather than the expected _buildout/bin_. This appears to be the result of a double-call to _Buildout._buildout_path()_ in _Builtout.__init__()_ if `directory` is set, both of which prepend the directory to the standard _*-directory_ paths.

The environment is buildout 2.2.1 installed via the latest version 2 bootstrap script run with Python 3.3.4 installed from the official repository on 64-bit Arch Linux.

A work-around is to set all the buildout _*-directory_ options explicitly.

**Comment by grant-humphries** [comment]
Can confirm that this bug still exists in recent versions of buildout.  Here are the basics of the environment that I'm running:

os = Windows 10
buildout = 2.13.0
setuptools = 40.6.3
python = 2.7/3.6

and the pertinent buildout config:

```ini
[buildout]
directory = .buildout
```

I thought this might be a Windows-based issue but given the initial post here that doesn't seem to be the case.  Here's the stack trace I'm getting:

```
Traceback (most recent call last):
  File "c:\users\humphrig\projects\test-trimet.trap\.venv\lib\site-packages\zc\buildout\buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "c:\users\humphrig\projects\test-trimet.trap\.venv\lib\site-packages\zc\buildout\buildout.py", line 659, in install
    self._setup_directories()
  File "c:\users\humphrig\projects\test-trimet.trap\.venv\lib\site-packages\zc\buildout\buildout.py", line 892, in _setup_directories
    os.mkdir(d)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '.buildout\\.buildout\\bin'
```

**Comment by gotcha** [comment]
What are you trying to achieve by setting the `directory` value ?

**Comment by grant-humphries** [comment]
@gotcha so the default behavior is for buildout to create several directories (`bin`, `develop_eggs`, `eggs`, `parts`, etc.) in a project's root along side the `buildout.cfg`.  I'd like all buildout generated files and folders to be written to a folder called `.buildout` that lives in the root directory.

This approach provides the abillity to ignore all files that should not be committed with a single entry in a `.gitignore` and to delete all buildout generated files with a single call to `rm`

From reading [the docs](http://www.buildout.org/en/latest/reference.html) I got the impression that the `directory` setting could be used to achieve this, is that incorrect?

**Comment by mgedmin** [comment]
It was always my impression that ${buildout:directory} was a readonly variable containing the directory that contains the buildout.cfg, so you could use it if you needed to provide an absolute directory computed relative to the project root anywhere else.

Apparently it's not actually readonly, but things break if you try to change it.

I think your reading of the documentation is a reasonable one, even if it was not meant to be interpreted that way.  I think the buildout maintainers ought to decide if they want to support changing `directory` and then either make it work, or make trying to set it an actual error (and update the docs).

Meanwhile I fear you'll have to set multiple variables (eggs-directory, parts-directory, bin-directory etc.) to relative paths .buildout/eggs, .buildout/parts etc. to get what you want.

**Comment by grant-humphries** [comment]
Can confirm that the workaround that @mgedmin (and @hashstat in the initial post) suggest works.   

I did find a little bit of inconsistency in the `*-directory` settings in that if they are put in place in an inherited config file (i.e. you have a `buildout.cfg` that inherits from `base.cfg` and the directory settings are in the base file) the sub folder being written to must exist or buildout will throw an error, while if they're in the file buildout initially reads (`buildout.cfg` in this example) the sub directory gets created.

Getting back to the discussion, am just curious, what would be an example of changing the value of `directory` in the way that was intended by the buildout devs?

**Comment by mauritsvanrees** [comment]
Just as another example, in the core development buildout of Plone we have [`plips/plipbase.cfg`](https://github.com/plone/buildout.coredev/blob/5.1/plips/plipbase.cfg) which sets several directories.

```
[buildout]
extends = ../core.cfg
develop-eggs-directory = ../develop-eggs
bin-directory = ../bin
parts-directory = ../parts
sources-dir = ../src
installed = ../.installed.cfg
eggs += Plone

[instance]
var = ${buildout:directory}/../var
```

Huh, we are not actually setting `directory` there, only a few similar ones.

**Comment by gotcha** [comment]
> Getting back to the discussion, am just curious, what would be an example of changing the value of `directory` in the way that was intended by the buildout devs?

I have the feeling that changing the value of `directory` is not foreseen by buildout devs...

We might need to forbid it.
