### ISSUE TITLE
buildout fails to get any version with multiple constrains, even if valid packages exist

### ISSUE THREAD

**Issue by do3cc** [buildout/buildout#264]
Here is a simple example:

```
[buildout]
parts = test

[test]
recipe = zc.recipe.egg
eggs =
    plone.formwidget.recurrence>1.0.0
    plone.formwidget.recurrence<2.0.0
```
From the package in question exists a version 1.2.5 which should be findable.
Instead I get a traceback:
```
Getting distribution for 'plone.formwidget.recurrence>1.0.0'.
warning: no previously-included files matching '*pyc' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
Got plone.formwidget.recurrence 2.0.1.
Getting distribution for 'plone.formwidget.recurrence<2.0.0'.
warning: no previously-included files matching '*pyc' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
While:
  Installing test.
  Getting distribution for 'plone.formwidget.recurrence<2.0.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/private/tmp/bla/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/private/tmp/bla/lib/python2.7/site-packages/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/private/tmp/bla/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/private/tmp/bla/eggs/zc.recipe.egg-2.0.2-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/private/tmp/bla/eggs/zc.recipe.egg-2.0.2-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/private/tmp/bla/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/private/tmp/bla/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/private/tmp/bla/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 549, in _get_dist
    dist = self._env.best_match(requirement, ws)
  File "/private/tmp/bla/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1074, in best_match
    dist = working_set.find(req)
  File "/private/tmp/bla/lib/python2.7/site-packages/pkg_resources/__init__.py", line 711, in find
    raise VersionConflict(dist, req)
VersionConflict: (plone.formwidget.recurrence 2.0.1 (/private/tmp/bla/eggs/plone.formwidget.recurrence-2.0.1-py2.7.egg), Requirement.parse('plone.formwidget.recurrence<2.0.0'))
```

This change which introduced this behaviour:
https://github.com/buildout/buildout/commit/58d44373c3e21d28eea9c88eebc1f7bed08d849d

I am not sure, what would be the right way to fix that. The comment above the traceback suggests, that originally the traceback would have been catched by something

**Comment by reinout** [comment]
Buildout treats both of the lines separately. There is no code that tries to combine requirement lines if you yourself specify them separately.

Is that functionality that buildout really needs? You can just as well write it as:

    plone.formwidget.recurrence>1.0.0<2.0.0

Right? The error occurs because two conflicting requirements have been specified (on separate lines).

If it would be up to buildout to fix it, the fix would be near the top of the `install()` method, before the line where requirements are constructed from the specs: here some spec-parsing would need to happen to combine the 'eggs' lines.

Now.... The same kind of error might occur later on in the code if one of the requirements itself has a dependency with a version constrain that conflicts with an already-found package. A possible fix would be to re-start the entire 'install' method with an extra spec (constraining the version-conflict-generating package). I don't know how that can be done easily. (Note: this would *also* need the combine-the-specs fix :-) )

**Comment by do3cc** [comment]
The example above is contrived. The real example had two eggs, one requiring bla[z3csomeing]
the other bla<2.0.0
The error is the same. I was many years ago told that this is one of the core features that zc.buildout provides and easy_install doesn't

**Comment by do3cc** [comment]
and yes, the line you provided looks about right. and plone.formwidget.recurrence 1.2.5 would match that spec and exists

**Comment by reinout** [comment]
Making sure: the problem really is with the contents of such an `eggs=` line? Not with requirements buried somewhere inside the dependencies of a sub-requirement?

**Comment by do3cc** [comment]
I don't understand. the example above fails.
Are you suggesting that the example is meant to fail, and an example with two different eggs, depending on pfc with different constrains should not fail?

**Comment by jimfulton** [comment]
The issue is that buildout searches for requirements in the order given and *doesn't* backtrack.
Your first requirement plone.formwidget.recurrence>1.0.0, is satisfied by plone.formwidget.recurrence 2.0.1, but that violates the second requirement.  This is a limitation in buildout's (and setuptools) requirement-resolution algorithm.

The fact that you stated 2 separate requirements for the same package is a bit of a red herring. As you point out the same effect could have been achieved by depending on independent dependencies that had these restrictions.

The work around in a situation like this is to rearrange the requirement order or to specify a specific version that satisfies the requirements.

A better requirements-resolution algorithm would be an worthy contribution. :)

**Comment by reinout** [comment]
What I'm meaning is that the example fails in a different part of the code. Different than the packages-depending-on-pfc-with-different-constraints would fail in.

Your example can be fixed by combining the requirements (or by saying "don't write conflicting requirements but combine them yourself").

The constraints-error-in-dependencies requires a much bigger fix (I think).

**Comment by reinout** [comment]
For a better fix, it would be necessary to get better information out of setuptools than we're currently getting. So... I thought somebody wanted to build a base level tool to handle installing which could then be used by real installers like buildout. Anyone know the status? I'll browse through the distutils-sig mailinglist a bit.

**Comment by leorochael** [comment]
As base level tool I would suggest [distlib](https://bitbucket.org/pypa/distlib). It's a dependency (vendored) of pip itself.

**Comment by reinout** [comment]
The readme on bitbucket is meagre, but here's a lot of docs: http://distlib.readthedocs.org/en/latest/ :-)

**Comment by reinout** [comment]
I've created a PR #282 that at least prints out much better version conflict information.

**Comment by djay** [comment]
@reinout @jimfulton The root cause of this problem is you can't get version dependencies from eggs until you have downloaded them and run setup.py and also because that is done at a lower level inside a recipe rather as part of buildout syntax itself. (ie you can just read a buildout.cfg and know what eggs are installed without running the recipes).

I think it might be possible to introduce backtracking which is one solution to solve this. Each time the working set is updated a copy is made associated with a recipe. We now have the where the constraints come from. So as soon as a conflict is hit, we backtrack to where that egg was first requested, but this time keeping the new constraint that conflicted (but discarding any others collected) and reinstall that from that part.
It wouldn't be very efficient but at least it would keep going. Hopefully not in a loop :)
It might just work, at least until we get a better pypi that can give us dependency information in advance.
