### ISSUE TITLE
Dependency parsing broken with setuptools-20.2.1

### ISSUE THREAD

**Issue by dz0ny** [buildout/buildout#286]
```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/mnt/ssd/ebn/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/mnt/ssd/ebn/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/mnt/ssd/ebn/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/mnt/ssd/ebn/eggs/zc.recipe.egg-2.0.1-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/mnt/ssd/ebn/eggs/zc.recipe.egg-2.0.1-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/mnt/ssd/ebn/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 883, in install
    return installer.install(specs, working_set)
  File "/mnt/ssd/ebn/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 724, in install
    extra_requirements = dist.requires(req.extras)[::-1]
  File "/mnt/ssd/ebn/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2462, in requires
    dm = self._dep_map
  File "/mnt/ssd/ebn/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2457, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/mnt/ssd/ebn/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2762, in parse_requirements
    req = packaging.requirements.Requirement(line)
  File "/mnt/ssd/ebn/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'!= 2.4'"
```
This happens if package defined as flake = 5.2.1 contains alternate dependency requirement:
$ cat eggs/flake8-2.5.1-py2.7.egg/EGG-INFO/requires.txt
```
pyflakes >= 0.8.1
pep8 >= 1.5.7, != 1.6.0, != 1.6.1, != 1.6.2
mccabe >= 0.2.1
```
This is one example but happens for many packages.

**Comment by do3cc** [comment]
Did you test if this is new with 20.2.1 or is it also broken with, lets say 18.0.0?

**Comment by dz0ny** [comment]
It's new with 20.2.1 older versions work fine

**Comment by do3cc** [comment]
It seems to be a problem in setuptools: https://bitbucket.org/pypa/setuptools/issues/499
I would wait and see

**Comment by do3cc** [comment]
And [501](https://bitbucket.org/pypa/setuptools/issues/501) and [502](https://bitbucket.org/pypa/setuptools/issues/502)

**Comment by do3cc** [comment]
@dz0ny did 20.2.2 solve the problem for you?

**Comment by dz0ny** [comment]
Yep resolved :)
