### ISSUE TITLE
error while removing tmp file on windows when downloading extends fails

### ISSUE THREAD

**Issue by lck** [buildout/buildout#31]
when running on windows, and the buildout fails to download the extends, the windows error is raised because the tmp file is locked:

here is the code that failes, download.py, line 179 - 187:

```
        try:
            tmp_path, headers = urllib.urlretrieve(url, tmp_path)
            if not check_md5sum(tmp_path, md5sum):
                raise ChecksumError(
                    'MD5 checksum mismatch downloading %r' % url)
        except IOError, e:
            os.remove(tmp_path)
            raise zc.buildout.UserError("Error downloading extends for URL"
                                        " %s: %r" % (url, e[1:3]))
```

the os.remove(tmp_path) raises following error on windows:

Traceback (most recent call last):
  File "C:\Buildouts\plone43wsgi\lib\site-packages\zc\buildout\buildout.py", line 1851, in main
    command)
  File "C:\Buildouts\plone43wsgi\lib\site-packages\zc\buildout\buildout.py", line 203, in **init**
    data['buildout'].copy(), override, set()))
  File "C:\Buildouts\plone43wsgi\lib\site-packages\zc\buildout\buildout.py", line 1489, in _open
    downloaded)
  File "C:\Buildouts\plone43wsgi\lib\site-packages\zc\buildout\buildout.py", line 1434, in _open
    path, is_temp = download(filename)
  File "C:\Buildouts\plone43wsgi\lib\site-packages\zc\buildout\download.py", line 99, in __call__
    local_path, is_temp = self.download(url, md5sum, path)
  File "C:\Buildouts\plone43wsgi\lib\site-packages\zc\buildout\download.py", line 185, in download
    os.remove(tmp_path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\users\rlacko~1.tem\appdata\local\temp\buildout-1qrvkz'

Due this error the real error message [1] is not shown to user

[1] raise zc.buildout.UserError("Error downloading extends for URL"...

**Comment by ljluestc** [comment]
```
import os
import urllib.request
import hashlib

class ChecksumError(Exception):
    pass

def check_md5sum(file_path, expected_md5):
    """Check if the MD5 checksum of the file matches the expected checksum."""
    with open(file_path, 'rb') as f:
        file_data = f.read()
    md5sum = hashlib.md5(file_data).hexdigest()
    return md5sum == expected_md5

def download_file(url, expected_md5, tmp_path):
    """
    Download a file from the given URL to tmp_path.
    Check its MD5 checksum and if there is an IOError during download,
    attempt to remove the temporary file (ignoring any removal errors).
    """
    try:
        # Download the file
        tmp_path, headers = urllib.request.urlretrieve(url, tmp_path)
        # Check MD5 checksum
        if not check_md5sum(tmp_path, expected_md5):
            raise ChecksumError(f"MD5 checksum mismatch downloading {url}")
    except IOError as e:
        try:
            os.remove(tmp_path)
        except Exception as remove_error:
            # Log the removal error, but don't block the real exception
            print(f"Warning: error removing temporary file: {remove_error}")
        raise Exception(f"Error downloading extends for URL {url}: {e}")
    return tmp_path

# Example usage:
if __name__ == '__main__':
    url = "http://example.com/file.ext"  # Replace with actual URL
    expected_md5 = "d41d8cd98f00b204e9800998ecf8427e"  # Replace with expected MD5 checksum
    tmp_path = os.path.join(os.environ.get('TEMP', '.'), "buildout_tmp_file")

    try:
        downloaded_path = download_file(url, expected_md5, tmp_path)
        print("Downloaded file to:", downloaded_path)
    except Exception as e:
        print(e)

```
