### ISSUE TITLE
Failed assertion due to case confusion (on Windows)

### ISSUE THREAD

**Issue by chrullrich** [buildout/buildout#385]
```
[buildout]
parts = django

[django]
recipe = zc.recipe.egg:eggs
eggs = Django <1.11
```

```
> bin\buildout --version
`buildout version 2.9.3`
> bin\buildout
Upgraded:
  setuptools version 28.8.0;
restarting.
Generated script 'C:\\Daten\\Projekte\\D\\dj\\test\\bin\\buildout'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
Installing django.
Getting distribution for 'Django<1.11'.
no previously-included directories found matching 'django\contrib\admin\bin'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
While:
  Installing django.
  Getting distribution for 'Django<1.11'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\daten\projekte\d\dj\test\eggs\zc.buildout-2.9.3-py3.6.egg\zc\buildout\buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "c:\daten\projekte\d\dj\test\eggs\zc.buildout-2.9.3-py3.6.egg\zc\buildout\buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\daten\projekte\d\dj\test\eggs\zc.buildout-2.9.3-py3.6.egg\zc\buildout\buildout.py", line 1553, in _call
    return f()
  File "c:\daten\projekte\d\dj\test\eggs\zc.recipe.egg-2.0.3-py3.6.egg\zc\recipe\egg\egg.py", line 89, in install
    reqs, ws = self.working_set()
  File "c:\daten\projekte\d\dj\test\eggs\zc.recipe.egg-2.0.3-py3.6.egg\zc\recipe\egg\egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "c:\daten\projekte\d\dj\test\eggs\zc.buildout-2.9.3-py3.6.egg\zc\buildout\easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "c:\daten\projekte\d\dj\test\eggs\zc.buildout-2.9.3-py3.6.egg\zc\buildout\easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "c:\daten\projekte\d\dj\test\eggs\zc.buildout-2.9.3-py3.6.egg\zc\buildout\easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "c:\daten\projekte\d\dj\test\eggs\zc.buildout-2.9.3-py3.6.egg\zc\buildout\easy_install.py", line 1730, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
AssertionError
```

The cause is in easy_install.py line 1659:

```
1658: dist_infos = [ (d.project_name, d.version) for d in dists ]
1659: if dist_infos == [(dist.project_name, dist.version)]:
```

The project name in `dist_infos[0][0]` has somehow become lower case, so the comparison fails. easy_install is aware of case insensitivity issues elsewhere, and it looks like it is getting itself into trouble somewhere by lowercasing the name.

Fix: .lower() the project_name in both lines.

**Comment by chrullrich** [comment]
No, it's pkg_resources that does the deed. It feeds the distribution names through `os.path.normcase()`; that function cleverly does nothing on platforms with case-sensitive file systems, but lowercases its argument on Windows.

If setuptools accepts case-insensitively-equal names as referring to the same package, I think buildout should do the same.

**Comment by daybarr** [comment]
buildout/buildout.wheel#11 also has the same underlying cause (`pkg_resources` feeding the distribution names through `os.path.normcase()`)
