### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by iivvoo** [buildout/buildout#387]
Starting with a minimal, fresh buildout setup using python3.5 and the latest (2.9.3) buildout from pip results in the error

```
$ bin/buildout -c buildout.cfg 
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
While:
  Installing.
  Getting section bobo.
  Initializing section bobo.
  Installing recipe zc.recipe.egg.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/buildout.py", line 680, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/buildout.py", line 680, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/buildout.py", line 1274, in __getitem__
    options._initialize()
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/buildout.py", line 1382, in _initialize
    self.initialize()
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/buildout.py", line 1388, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/buildout.py", line 1338, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/zc/buildout/easy_install.py", line 666, in install
    ws.add(dist)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 791, in add
    self._added_new(dist)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 991, in _added_new
    callback(dist)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3006, in <lambda>
    add_activation_listener(lambda dist: dist.activate(replace=True), existing=False)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2532, in activate
    fixup_namespace_packages(self.location)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2120, in fixup_namespace_packages
    subpath = _handle_ns(package, path_item)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2058, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/ivo/m3r/projects/GUTS/bo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2078, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

```

This is in a clean, empty virtualenv (python3.5) with pip installed (pip freeze attached below). The buildout.cfg looks as follows:

```
[buildout]
parts = sample

[sample]
recipe = zc.recipe.egg
eggs = requests
```

Downgrading to buildout 2.5.3 resolves the issue (I picked that version because it works for me on other projects).

This issue has been reported elsewhere in other contexts, the real fix is unclear. But since a downgrade of buildout solves the problem, an additional fix in buildout might be necessary.

pip freeze:

```
$ bin/pip freeze
appdirs==1.4.3
packaging==16.8
pkg-resources==0.0.0
pyparsing==2.2.0
six==1.10.0
zc.buildout==2.9.3
```

**Comment by beary** [comment]
I met the same problem when I buildout as "getting-started" document said. ([http://docs.buildout.org/en/latest/getting-started.html#installing-software](http://docs.buildout.org/en/latest/getting-started.html#installing-software))
Python 3.6.1
buildout 2.9.3

And this problem was resolved after I use buildout 2.8.0. I have tried 2.9.0 but it didn't work.

**Comment by leorochael** [comment]
Could not reproduce this with Python 3.4.3 on Ubuntu 14.04 (yeah, I need to upgrade dev system) and the following package versions (according to `pip freeze --all`):

```
appdirs==1.4.3
packaging==16.8
pip==9.0.1
pyparsing==2.2.0
setuptools==35.0.2
six==1.10.0
zc.buildout==2.9.3
```

@iivvoo, @beary. Can you tell us what version of `setuptools` you're using? Or alternatively, show us the output of `pip freeze --all`?

**Comment by iivvoo** [comment]
```
$ bin/pip freeze --all
appdirs==1.4.3
packaging==16.8
pip==9.0.1
pkg-resources==0.0.0
pyparsing==2.2.0
setuptools==35.0.2
six==1.10.0
wheel==0.30.0a0
zc.buildout==2.9.3
```

**Comment by leorochael** [comment]
@iivvoo, what's that `pkg-resources==0.0.0` you got there?

I know people have talked about splitting `pkg_resources` out of `setuptools` for ages, but AFAICT it [hasn't happened yet](https://github.com/pypa/setuptools/tree/master/pkg_resources).

**Comment by iivvoo** [comment]
It seems to be something that comes with a fresh empty virtualenv:

```
$ virtualenv -p /usr/bin/python3.5 bo2
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /home/ivo/tmp/bo2/bin/python3.5
Also creating executable in /home/ivo/tmp/bo2/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$ bo2/bin/pip freeze --all
appdirs==1.4.3
packaging==16.8
pip==9.0.1
pkg-resources==0.0.0
pyparsing==2.2.0
setuptools==35.0.2
six==1.10.0
wheel==0.30.0a0
```
```
$ find . -name pkg\*
./lib/python3.5/site-packages/pkg_resources
./lib/python3.5/site-packages/pkg_resources-0.0.0.dist-info
./lib/python3.5/site-packages/wheel/pkginfo.py
./lib/python3.5/site-packages/wheel/__pycache__/pkginfo.cpython-35.pyc
./lib/python3.5/site-packages/pip/_vendor/pkg_resources
./share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl

```

**Comment by leorochael** [comment]
@iivvoo.

Clearly, you have a pkg_resources package coming from somewhere, but there isn't one on PyPI, so I'm at a loss to explain where it comes from.

Until we find it, I have no way to reproduce what's happening to you...

**Comment by leorochael** [comment]
Ok, so there is a [year old `pkg_resources`](https://github.com/pypa/pkg_resources) repo, and it even has a [0.1.0 release](https://github.com/pypa/pkg_resources/releases).

But that still doesn't explain how your virtualenv got a 0.0.0 wheel, so I'm still confused about what's happening to @iivvoo.

**Comment by beary** [comment]
@leorochael 
```
$ pyenv install 3.6.1
...
$ pyenv virtualenv 3.6.1 env361
...
$ pyenv local env361

(env361) $ pip install zc.buildout
...

(env361) $ pip freeze --all
pip==9.0.1
setuptools==28.8.0
zc.buildout==2.9.3

(env361) $ buildout
Creating directory '/home/beary/py-work/zc-test/eggs'.
Creating directory '/home/beary/py-work/zc-test/bin'.
Creating directory '/home/beary/py-work/zc-test/parts'.
Creating directory '/home/beary/py-work/zc-test/develop-eggs'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
While:
  Installing.
  Getting section bobo.
  Initializing section bobo.
  Installing recipe zc.recipe.egg.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/buildout.py", line 680, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/buildout.py", line 680, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/buildout.py", line 1274, in __getitem__
    options._initialize()
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/buildout.py", line 1382, in _initialize
    self.initialize()
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/buildout.py", line 1388, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/buildout.py", line 1338, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 666, in install
    ws.add(dist)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/pkg_resources/__init__.py", line 790, in add
    self._added_new(dist)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/pkg_resources/__init__.py", line 990, in _added_new
    callback(dist)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3047, in <lambda>
    add_activation_listener(lambda dist: dist.activate(replace=True), existing=False)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2574, in activate
    fixup_namespace_packages(self.location)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2162, in fixup_namespace_packages
    subpath = _handle_ns(package, path_item)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/beary/.pyenv/versions/3.6.1/envs/env361/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

**Comment by k4ml** [comment]
Initially got this error too:-

```
venv/bin/pip freeze --all
pip==9.0.1
setuptools==30.2.0
virtualenv==15.0.3
zc.buildout==2.9.3
```

Created the venv with `python3 -mvenv venv`, using python-3.6.1. But after running `venv/bin/pip install -U setuptools`, the issue go away. PIP now showing this:-

```
venv/bin/pip freeze --all
appdirs==1.4.3
packaging==16.8
pip==9.0.1
pyparsing==2.2.0
setuptools==30.2.0
six==1.10.0
virtualenv==15.0.3
zc.buildout==2.9.3
```

**Comment by svenevs** [comment]
Hi All,

As @k4ml indicates, you need to update `setuptools`.  I personally just upgraded the system `setuptools` (with `sudo -H pip3 install -U setuptools`).

My understanding is that `buildout` could catch the `AttributeError: '_NamespacePath' object has no attribute 'sort'` and instead of reporting `An internal error occurred due to a bug in either zc.buildout or in a recipe being used:` it could change the message to suggest updating the system `setuptools`.

Or maybe there is a more buildout-appropriate way of upgrading `setuptools` locally?  E.g. perhaps the best solution, since `buildout` for python stuff is going to use `easy_install` (I believe), is to find a way to automatically install a local `setuptools` egg?  I'm very new to buildout and don't know if any of that is appropriate.

Alternatively, a super easy hack for the `buildout` team would be to mark in their `setup_requires` an explicit version of `setuptools` (e.g. if this `sort` method was introduced in v30.0 require `setuptools>=30.0.0`), and thus when anybody does `pip3 install zc.buildout` everything will automatically be ready :)
