### ISSUE TITLE
Incompatibility with pyenv

### ISSUE THREAD

**Issue by naftulikay** [buildout/buildout#408]
I am working on a Python 3 project with the following buildout configuration:

```
[buildout]
parts = python ipython test
develop = .
eggs = revolution
versions = versions

[versions]
ipython = 5.4

[python]
recipe = zc.recipe.egg
interpreter = python
eggs = ${buildout:eggs}

[test]
recipe = pbp.recipe.noserunner
eggs = ${buildout:eggs}
    pbp.recipe.noserunner
    mock
script = test

[ipython]
recipe = zc.recipe.egg:scripts
eggs = ${buildout:eggs}
    ipython
scripts = ipython
```

I have installed Python 3.5.3 via pyenv:

```
[vagrant@devel vagrant]$ pyenv list
pyenv: no such command `list'
[vagrant@devel vagrant]$ pyenv versions
  system
  2.7.13
* 3.5.3 (set by /vagrant/.python-version)
[vagrant@devel vagrant]$ python --version
Python 3.5.3
[vagrant@devel vagrant]$ which python
~/.pyenv/shims/python
```

However, when I run my code which simply does `from enum import Enum`, I get the following error:

```
[vagrant@devel vagrant]$ bin/python -c 'from enum import Enum'
Traceback (most recent call last):
  File "bin/python", line 23, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
ImportError: No module named enum
```

Is there an incompatibility between buildout and pyenv?

**Comment by naftulikay** [comment]
My bad, this was my fault, had buildout installed in the wrong place.
