### ISSUE TITLE
An internal error occurred due to a bug in either zc.buildout or in a recipe being used

### ISSUE THREAD

**Issue by ggkitsas** [buildout/buildout#411]
Hello,

I am currently working on a project that uses buildout during setup.
I am getting the following error when invoking `./bin/buildout` :
```
While:
  Installing.
  Getting section django.
  Initializing section django.
  Installing recipe djangorecipe.
  Getting distribution for 'Django==1.8.13'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 680, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1274, in __getitem__
    options._initialize()
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1382, in _initialize
    self.initialize()
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1388, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1338, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/easy_install.py", line 714, in install
    for dist in self._get_dist(req, ws):
  File "/home/cyc0/Projects/wisefilepro/mysafeplace-bak/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/easy_install.py", line 570, in _get_dist
    dist = self._env.best_match(requirement, ws)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1111, in best_match
    dist = working_set.find(req)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 715, in find
    raise VersionConflict(dist, req)
VersionConflict: (Django 1.11.4 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('Django==1.8.13'))
```
I have also created an [issue](https://github.com/rvanlaar/djangorecipe/issues/96) to the [djangorecipe project](https://github.com/rvanlaar/djangorecipe).
Not sure what else shall I share here since I am new user of buildout. 

Thank you!

**Comment by jamadden** [comment]
I believe what that's telling your buildout has requested is that Django version 1.8.13, but Django version 1.11.4 is already installed as a system package in `/usr/local/lib/python2.7/dist-packages`. buildout does not provide isolation from system packages, so it can't meet the 1.18.13 requirement.

You could try uninstalling the system package (it was probably installed with the operating system's package manager so that's what you would use to uninstall it). Or you could try running the buildout in a virtualenv without access to the system packages (it isolates you from site-packages, I'm not 100% sure whether that includes dist-packages or not).

**Comment by jimfulton** [comment]
A virtualenv should work.

**Comment by reinout** [comment]
Uninstalling the global version (or using a virtualenv) should work.

The 'problem' is that buildout first installs the recipes and afterwards it installs all the other dependencies. The second step has no problem with globally installed packages, but the recipe-installing step does. And djangorecipe has a direct dependency on django (to make sure it is installed)...

Anyway, not a buildout problem.

Best solution: remove the globally installed django.

**Comment by ggkitsas** [comment]
Thanks all! The local django package was the issue indeed.
