### ISSUE TITLE
cannot install django using djangorecipe

### ISSUE THREAD

**Issue by ggkitsas** [buildout/buildout#414]
Hello,

I am trying to install django using djangorecipe and got the following error:

```
While:
  Installing django.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/appuser/mysafeplace/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/appuser/mysafeplace/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/appuser/mysafeplace/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/appuser/mysafeplace/eggs/djangorecipe-2.1.2-py2.7.egg/djangorecipe/recipe.py", line 89, in install
    extra_paths, ws)
  File "/home/appuser/mysafeplace/eggs/djangorecipe-2.1.2-py2.7.egg/djangorecipe/recipe.py", line 172, in create_scripts_with_settings
    known_entrypoints = list(ws.iter_entry_points('console_scripts'))
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 726, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2639, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2369, in parse_map
    for group, lines in data:
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2967, in split_sections
    for line in yield_lines(s):
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2235, in yield_lines
    for ss in strs:
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2564, in _get_metadata
    if self.has_metadata(name):
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1458, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1818, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1698, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1637, in load
    path = os.path.normpath(path)
  File "/usr/lib/python2.7/posixpath.py", line 342, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```
The build runs inside a docker container and I've made sure that there is no django installed in that system. Any hints on what this error means?

Thanks!

**Comment by jamadden** [comment]
That's a very similar traceback as what's in https://github.com/buildout/buildout/issues/406, which was closed, but has additional comments indicating that it's still a problem.

Can you try pinning zc.recipe.egg to 2.0.3 and seeing if it works?

**Comment by ggkitsas** [comment]
Thank you @jamadden ! That solved my issue.

**Comment by jamadden** [comment]
I'm glad that solved your problem! But it seems like there's a real issue in zc.recipe.egg 2.0.4.

**Comment by ggkitsas** [comment]
Just went to open an issue but you got there first.
