### ISSUE TITLE
AttributeError with zc.recipe.egg 2.0.4

### ISSUE THREAD

**Issue by jamadden** [buildout/buildout#415]
Different users on different platforms (OS X and Linux) with different third-party recipes  have reported variations on this traceback:

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/appuser/mysafeplace/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/appuser/mysafeplace/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/appuser/mysafeplace/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/appuser/mysafeplace/eggs/djangorecipe-2.1.2-py2.7.egg/djangorecipe/recipe.py", line 89, in install
    extra_paths, ws)
  File "/home/appuser/mysafeplace/eggs/djangorecipe-2.1.2-py2.7.egg/djangorecipe/recipe.py", line 172, in create_scripts_with_settings
    known_entrypoints = list(ws.iter_entry_points('console_scripts'))
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 726, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2639, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2369, in parse_map
    for group, lines in data:
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2967, in split_sections
    for line in yield_lines(s):
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2235, in yield_lines
    for ss in strs:
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2564, in _get_metadata
    if self.has_metadata(name):
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1458, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1818, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1698, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1637, in load
    path = os.path.normpath(path)
  File "/usr/lib/python2.7/posixpath.py", line 342, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

This goes away with zc.recipe.egg 2.0.3, so the (caching) changes in 2.0.4 are apparently interacting badly with some use cases and recipes.

See #414 and #406

**Comment by leorochael** [comment]
If I could get a minimal reproducible test case, that would help a lot.

**Comment by rafaelbco** [comment]
I'll be glad to help since I implemented the changes that went into 2.0.4. However I don't know where to start without a buildout that reproduces the problem.

**Comment by jamadden** [comment]
The buildout in #406 that reproduces this is eye-watteringly complex. Maybe @ggkitsas (from #414) has a simpler starting example?

**Comment by rafaelbco** [comment]
Yes. And also we were not able to reproduce the error using the given example.

**Comment by jamadden** [comment]
Ping @ggkitsas, just in case they can provide a simpler starting example?

**Comment by hvelarde** [comment]
you can reproduce this issue by cloning [this repo](https://github.com/plonegovbr/portal.buildout) and updating version of zc.recipe.egg to 2.0.5 in [this file](https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg).

the problem is not present using zc.recipe.egg 2.0.3 as stated above; I think this points to an issue on the recipe.

**Comment by jamadden** [comment]
So far I can't reproduce a problem in the repo @hvelarde pointed to.

Steps:

1) Create a new temporary virtualenv with python 2.7
2) install zc.buildout 2.10.0
3) clone the repo
4) Edit buildout.d/versions.cfg to specify the required versions.
5) `buildout -c travis-development.cfg` (because there are several so I guessed)
6) Wait a long time 😄 

I'm on macOS and several of the dependencies are too old and don't properly support macOS so I had to modify more than zc.buildout and zc.recipe.eggs and setuptools dependencies:

```patch
modified: buildout.d/versions.cfg
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -28,7 +28,7 @@ extends =
     http://dist.plone.org/release/4.3.15/versions.cfg

 [versions]
-argh = 0.23.3
+argh = 0.26.2
 brasil.gov.agenda = 1.1.2
 brasil.gov.barra = 1.2.2
 brasil.gov.facetada = 1.0b1
@@ -150,7 +150,7 @@ SPARQLWrapper = 1.5.2
 superlance = 0.11
 supervisor = 3.1.4
 transmogrify.dexterity = 1.6.1
-watchdog = 0.6.0
+watchdog = 0.8.3
 z3c.jbot = 0.7.2
 z3c.pt = 3.0.0a1
 z3c.recipe.usercrontab = 1.2.1
@@ -159,9 +159,9 @@ z3c.unconfigure = 1.1
 # por padrão uma url http do pypi mas agora só é aceito https. Favor ver
 # https://community.plone.org/t/disabling-non-https-access-to-apis-on-pypi/5069/12
 # para mais detalhes.
-zc.buildout = 2.9.5
+zc.buildout = 2.10.0
 # XXX: https://github.com/buildout/buildout/issues/415
-zc.recipe.egg = 2.0.3
+zc.recipe.egg = 2.0.5
 zope.app.locales = 3.7.4
 zope.configuration = 3.8.1

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: development.cfg
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -18,7 +18,6 @@ parts +=
     robot
     test
     test-dependencies
-    versions-dump
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: travis-development.cfg
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -21,4 +21,4 @@ eggs =

 [versions]
 # use setuptools version included by virtualenv in Trusty
-setuptools = 36.3.0
+setuptools = 38.2.4
```

I also tried bootstrapping directly and sticking with the outdated versions of zc.buildout and setuptools, and that also appeared to work:
```console
$ cp travis-development.cfg buildout.cfg
$ python bootstrap.py --setuptools-version=36.3.0 --buildout-version=2.9.5
$ bin/buildout
...
Generated script '/.../tmp-6bee7375e54806e5/portal.buildout/bin/test-dependencies'.
```

I couldn't use travis-production.cfg, it also conains linux-specific parts:
```
Installing haproxy-build.
haproxy-build: Unpacking and configuring
gcc -Iinclude -Iebtree -Wall  -O2 -g       -DTPROXY -DCONFIG_HAP_CRYPT -DENABLE_POLL -DENABLE_EPOLL -DENABLE_SEPOLL -DNETFILTER -DUSE_GETSOCKNAME  -DCONFIG_HAPROXY_VERSION=\"1.4.8\" -DCONFIG_HAPROXY_DATE=\"2010/06/16\" \
	      -DBUILD_TARGET='"linux26"' \
	      -DBUILD_ARCH='""' \
	      -DBUILD_CPU='"generic"' \
	      -DBUILD_CC='"gcc"' \
	      -DBUILD_CFLAGS='"-O2 -g"' \
	      -DBUILD_OPTIONS='""' \
	       -c -o src/haproxy.o src/haproxy.c
In file included from src/haproxy.c:54:
In file included from include/common/cfgparse.h:25:
include/common/compat.h:66:10: fatal error: 'linux/types.h' file not found
#include <linux/types.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [src/haproxy.o] Error 1
While:
  Installing haproxy-build.
```

I use a global (`~/.buildout/default.cfg`) egg and download cache, if that makes any difference...

**Comment by hvelarde** [comment]
maybe using a newer version of setuptools fix the problem (we're using 26.1.1 as pinned in Plone 4.3 versions file); I'll take note of that, thanks!

**Comment by cosven** [comment]
I have met the same problem

**The way to reproduce:**
1. install with zc.buildout version  or up (tested with 2.9.4)
1. remove built-in setuptools **important**
2. create a new project and add a recipe which use setuptools as one dependency

**The second way to reproduce**
1. install with zc.buildout version  or up (tested with 2.5.0)
2. create a new project and add a recipe which use setuptools as one dependency

ps: the latest zc.recipe.egg is 2.0.5, both two case can reproduce. But if we downgrade to 2.0.3, it's ok.

**The potential problem in caching strategy**
```
import copy
from zipimport import zipimporter


path = 'eggs/xxx.egg'
importer = zipimporter(path)
assert importer.archive is not None

importer_copy = copy.deepcopy(importer)
assert importer_copy.archive is None
```
see <https://github.com/buildout/buildout/blob/master/zc.recipe.egg_/src/zc/recipe/egg/egg.py#L168>
In my opinion, it may be unsafe to use copy.deepcopy here.

cc @rafaelbco

**Comment by leorochael** [comment]
So, deepcopying a zipimporter is unsafe. But the caching in zc.recipe.egg deepcopies WorkingSets.

I tried to see how a zipimporter gets deepcopied when deepcopying a WorkingSet, but couldn't reproduce it quickly.

@cosven, can you show us the link between WorkingSets and zipimporters?

**Comment by cosven** [comment]
### Rational

1. WorkingSet is a collection of active distributions. 
2. Each Distribution has an attr named [`_provider`](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L2540).
3. Provider have an attr named [`loader`](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1469)

The loader of a [`ZipProvider`](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1683) is a zipimporter ([ref](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1855)).

As a result, if a (zipped egg) distribution is in workingset, the workingset can not be deepcopied.

That's why, in theory, I said it's unsafe to deepcopy workingset. @leorochael 

### Our usage scenario
In order to solve some problems (Currently, I dont know what exactly the problem is, whatever), we have our own buildout deb package.
As I pasted above, the buildout command we have is a litter bit different from official.

So in our case, the `eggs/setuptools-36.0.1-py2.7.egg` will be the (zipped egg) distribution.

**But** I do think this maybe a problem with our buildout deb package.

**Comment by leorochael** [comment]
> ### Rational
> 
> 1. WorkingSet is a collection of active distributions. 
> 2. Each Distribution has an attr named [`_provider`](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L2540).
> 3. Provider have an attr named [`loader`](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1469)
> 
> The loader of a [`ZipProvider`](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1683) is a zipimporter ([ref](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1855)).

So, `WorkingSet`s, since they provide `__setstate__` are effectively advertising that they can be copied. The fact that they can't be safely copied when containing a Distribution with a `ZipProvider` means, for me, that this is a bug in `WorkingSet` (i.e. a bug in `setuptools`).

AFAICT, Distributions, Providers and Importers are all immutable, so a deepcopy routine that didn't try to copy any of these objects, but simply pointed the copy to the previous instances of these classes, would fix this issue.

There are three strategies we could take at this point:

1. revert the cache

2. Make our own copy of the WorkingSet by iterating and adding all dists from the WorkingSet to a new one, instead of using `deepcopy()`

3. Fix WorkingSet in setuptools.

1 is easiest, but undesirable. 2 is almost as easy, but feels like a doing extra work just to avoid someone else's bug, which I personally find anoying :wink:.

My preference would be to go with 3: `setuptools` development is rather responsive these days, but it will require writing a test case that reproduces the bug.
