### ISSUE TITLE
Use importlib2 on Python2

### ISSUE THREAD

**Issue by leorochael** [buildout/buildout#421]
On a [message in distutils-sig](https://mail.python.org/pipermail/distutils-sig/2017-October/031752.html) Nick Coghlan mentioned that Python 2 scripts that use [`importlib2`](https://pypi.python.org/pypi/importlib2) can alleviate significantly some of the performance symptoms of the long `sys.path` generated by buildout that happen in certain cases like network disks or other high latency filesystems.

It might be a good idea to provide at least the option of adding the following call in the beginning of the preamble of scripts generated by buildout and zc.recipe.egg:

    import importlib2
    importlib2.hook.install()

I wonder if we can achieve it in an extension.

**Comment by jamadden** [comment]
I saw that message and I wondered the same thing. Some of our buildouts have almost 400 eggs put on sys.path. Scripts take slightly over a second to start, worst case.

I tried to add importlib2's hook to the top of such a script file to see if there was a measurable improvement, but it fails to even run the script.

```python
#!/home/.../.local/bin/python
# script.py
# generated by buildout, copied and modified by me
import importlib2.hook
importlib2.hook.install()
import sys
sys.path.extend([
    # 400 lines of eggs. Buildout does sys.path[0:0] = (...).
    # I tried that too.
    ...
])

import zope.app.form # This happens to be the last egg on the path
```

```
$ PYTHONPATH=importlib2-3.5.0.2 ./script.py
Traceback (most recent call last):
  File "./script.py", line 401, in <module>
    import zope.app.form
...
  File "/tmp/importlib2-3.5.0.2/importlib2/_fixers/__init__.py", line 184, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/.../buildout/eggs/zope.browserresource-4.2.1-py2.7.egg/zope/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/tmp/importlib2-3.5.0.2/importlib2/_bootstrap.py", line 2397, in __import__
    package = _calc___package__(globals_)
  File "/tmp/importlib2-3.5.0.2/importlib2/_bootstrap.py", line 2365, in _calc___package__
    package = globals['__name__']
```

It turns out that `globals` is an empty dictionary in this case. I was able to easily replicate this locally in a virtual environment:
```pycon
>>> import importlib2.hook
>>> importlib2.hook.install()
>>> __import__('pkg_resources')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/importlib2/_bootstrap.py", line 2396, in __import__
    package = _calc___package__(globals_)
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/importlib2/_bootstrap.py", line 2364, in _calc___package__
    package = globals['__name__']
KeyError: '__name__'
```

Simply importing `pkg_resources` directly also fails:
```pycon
>>> import importlib2.hook
>>> importlib2.hook.install()
>>> import pkg_resources
...
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/importlib2/_fixers/__init__.py", line 184, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 9, in <module>
    import os.path
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/importlib2/_bootstrap.py", line 2422, in __import__
    return sys.modules[module.__name__[:len(module.__name__)-cut_off]]
KeyError: 'posi'
```

If you import `pkg_resources` first, before installing the hook, you get a different error, but still an error. Actually, I got two different errors, depending on whether I was in a virtualenv with some other packages installed or not. First the virtualenv case:
```pycon
>>> import pkg_resources
>>> import importlib2.hook
>>> importlib2.hook.install()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//VirtualEnvs/tmp-9a8661b57e3b05e2/lib/python2.7/site-packages/importlib2/hook.py", line 62, in install
    inject()
  File "//VirtualEnvs/tmp-9a8661b57e3b05e2/lib/python2.7/site-packages/importlib2/hook.py", line 46, in inject
    _modules.inject_modules()
  File "//VirtualEnvs/tmp-9a8661b57e3b05e2/lib/python2.7/site-packages/importlib2/_fixers/_modules.py", line 412, in inject_modules
    inject_module(mod)
  File "//VirtualEnvs/tmp-9a8661b57e3b05e2/lib/python2.7/site-packages/importlib2/_fixers/_modules.py", line 392, in inject_module
    spec = _get_spec(mod)
  File "//VirtualEnvs/tmp-9a8661b57e3b05e2/lib/python2.7/site-packages/importlib2/_fixers/_modules.py", line 317, in _get_spec
    path = _get_path(mod)
  File "//VirtualEnvs/tmp-9a8661b57e3b05e2/lib/python2.7/site-packages/importlib2/_fixers/_modules.py", line 277, in _get_path
    return parent.__path__
AttributeError: 'module' object has no attribute '__path__'
```

(It turns out that the module it was looking at was `<module 'pyexpat.errors' (built-in)>` and `parent` was `<module 'pyexpat' from '/.../python2.7/lib-dynload/pyexpat.so'>`.)

And here's what happened in the buildout isolated case:
```
$ PYTHONPATH=/home/.../buildout/eggs/setuptools-33.1.1-py2.7.egg:importlib2-3.5.0.2 ./script.py
Traceback (most recent call last):
  File "./script.py", line 4, in <module>
    importlib2.hook.install()
  File "/tmp/importlib2-3.5.0.2/importlib2/hook.py", line 62, in install
    inject()
  File "/tmp/importlib2-3.5.0.2/importlib2/hook.py", line 49, in inject
    _modules.verify_modules()
  File "/tmp/importlib2-3.5.0.2/importlib2/_fixers/_modules.py", line 444, in verify_modules
    verify_module(mod, injected=injected)
  File "/tmp/importlib2-3.5.0.2/importlib2/_fixers/_modules.py", line 437, in verify_module
    raise RuntimeError(error.format(mod.__name__))
RuntimeError: 'email.parser' missing __spec__
```


This seems to be one or more bugs in importlib2 (because Python 3.x doesn't have this problem).  How they manifest is highly system/installation dependent.

**Comment by leorochael** [comment]
I see you tried to add the hook before the `sys.path.extend()` call.

Have you tried adding it after?

**Comment by jamadden** [comment]
Yes, that doesn't make any difference.

**Comment by leorochael** [comment]
> Yes, that doesn't make any difference.

Bummer... guess we should [report it](https://bitbucket.org/ericsnowcurrently/importlib2/issues?status=new&status=open) then...

**Comment by jamadden** [comment]
* 'missing `__spec__`': https://bitbucket.org/ericsnowcurrently/importlib2/issues/9/runtimeerror-no-spec-found-for-module (email.parser is a special lazy module)
* 'AttributeError: `__path__`': https://bitbucket.org/ericsnowcurrently/importlib2/issues/11/importlibhookinstall-fails-with
* 'KeyError: posi': https://bitbucket.org/ericsnowcurrently/importlib2/issues/12/importing-ospath-raises-keyerror (seen when importing 'os.path'; 'pkg_resources' has nothing to do with it)
* 'KeyError: `__name__`': https://bitbucket.org/ericsnowcurrently/importlib2/issues/13/__import__-module-with-no-globals-passed (seen for any use of `__import__('module')`)

**Comment by leorochael** [comment]
I see no point of leaving this open.
