### ISSUE TITLE
Can't install python-ldap maybe due to zope.org being down?

### ISSUE THREAD

**Issue by mtdeguzis** [buildout/buildout#433]
buildout/bin/buildout --version
buildout version 2.10.0

```
Download error on http://svn.zope.org/zc.buildout: [Errno -2] Name or service not known -- Some packages may not be found!
Updating _mr.developer.
Installing python.
Getting distribution for 'python-ldap'.
error: Couldn't find a setup script in /usr/lib64/python2.7/site-packages
An error occurred when trying to install /usr/lib64/python2.7/site-packages. Look above this message for any errors that were output by easy_install.
While:
  Installing python.
  Getting distribution for 'python-ldap'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.buildout-2.10.0-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.buildout-2.10.0-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.buildout-2.10.0-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.recipe.egg-2.0.5-py2.7.egg/zc/recipe/egg/egg.py", line 221, in install
    reqs, ws = self.working_set()
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.recipe.egg-2.0.5-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts,
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.recipe.egg-2.0.5-py2.7.egg/zc/recipe/egg/egg.py", line 162, in _working_set
    allow_hosts=allow_hosts)
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.buildout-2.10.0-py2.7.egg/zc/buildout/easy_install.py", line 920, in install
    return installer.install(specs, working_set)
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.buildout-2.10.0-py2.7.egg/zc/buildout/easy_install.py", line 672, in install
    for dist in self._get_dist(requirement, ws):
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.buildout-2.10.0-py2.7.egg/zc/buildout/easy_install.py", line 570, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/ghs_hdp_prod/audit-tools/buildout/eggs/zc.buildout-2.10.0-py2.7.egg/zc/buildout/easy_install.py", line 1700, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack
make: *** [build] Error 1
```

Snipped of my buildout.cfg
```
 10 [buildout]
 11 extensions = mr.developer
 12 versions = versions
 13 newest = true
 14 show-picked-versions = true
 15 sources = sources
 16 always-checkout = force
 17 auto-checkout = *
 18 parts =
 19     python
 20     scripts
 21     test

 31 index =
 32     https://pypi.python.org/pypi

 54 [python]
 55 recipe = zc.recipe.egg
 56 interpreter = python
 57 dependent-scripts = true
 58 eggs =
 59     nose
 60     opstools                  <--- my package pulled from a git source
 61     pep8
 62     psutil
 63     python-ldap            <--- added a few minutes ago to see if it as a chicken/egg issue. didn't help
 64     requests-kerberos
 65     thrift-sasl
 66     urllib3
 67
 68 [scripts]
 69 recipe = zc.recipe.egg:scripts
 70 eggs =
 71     nose
 72
 73 [test]
 74 recipe = zc.recipe.testrunner
 75 eggs =

```

My setup.py (which has always worked)
```
 35     install_requires=[
 36         'psutil',
 37         'ldap',
 38         'python-ldap',
 39         'pyhive[hive]',
 40         'requests',
 41         'requests-kerberos',
 42         'thrift-sasl',
 43         'urllib3',
 44     ],
```

**Comment by mtdeguzis** [comment]
Zope.org has lapsed:

![image](https://user-images.githubusercontent.com/27829577/33667027-b583df32-da69-11e7-8720-7883dc9a29da.png)

**Comment by jimfulton** [comment]
Yes, we know about zope.org. Unfortunately, it's out of our control.

No one should depend on anything under a zope.org domain. :(

(But svn.zope.org? really?)
