### ISSUE TITLE
buildout executable path doesn't compare because of lower/upper case on windows

### ISSUE THREAD

**Issue by projekt01** [buildout/buildout#453]
Using an executable in [buildout] section ends with an error on windows.

```
[buildout]
executable = C:\Python27\python.exe
```

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "d:\home\.buildout\eggs\zc.buildout-2.11.3-py2.7.egg\zc\buildout\buildout.py", line 2127, in main
    getattr(buildout, command)(args)
  File "d:\home\.buildout\eggs\zc.buildout-2.11.3-py2.7.egg\zc\buildout\buildout.py", line 797, in install
    installed_files = self[part]._call(recipe.install)
  File "d:\home\.buildout\eggs\zc.buildout-2.11.3-py2.7.egg\zc\buildout\buildout.py", line 1557, in _call
    return f()
  File "d:\home\.buildout\eggs\p01.recipe.setup-0.8.11-py2.7.egg\p01\recipe\setup\paste.py", line 153, in install
    eggs, ws = self.egg.working_set()
  File "d:\home\.buildout\eggs\zc.recipe.egg-1.3.2-py2.7.egg\zc\recipe\egg\egg.py", line 101, in working_set
    **kw)
  File "d:\home\.buildout\eggs\zc.buildout-2.11.3-py2.7.egg\zc\buildout\easy_install.py", line 915, in install
    assert executable == sys.executable, (executable, sys.executable)
AssertionError: ('C:\\Python27\\python.exe', 'c:\\python27\\python.exe')

```
Solution
---------
As workarround you can use lowercase path to the executable:
```
[buildout]
executable = c:\python27\python.exe
```

Regards
Roger Ineichen

**Comment by mgedmin** [comment]
`os.path.normpath()` ought to help

**Comment by reinout** [comment]
I looked at the code and I cannot actually find where that `executable` option is used. Apparently it *is*.

Where does the error occur? Is it perhaps inside a recipe? Buildout itself only seems to pass `sys.executable`.

**Comment by gotcha** [comment]
This seems to be a bad interaction with `zc.recipe.egg==1.3.2`. I'll close by declaring it outdated. Reopen if you know I am wrong !
