### ISSUE TITLE
"make build" on OSX fails with "urlopen error unknown url type: https"

### ISSUE THREAD

**Issue by khink** [buildout/buildout#456]
- checkout repo 
- `make build`

This installs a Python in `pythons/2.7` but then it fails with:
```
Traceback (most recent call last):
  File "dev.py", line 50, in <module>
    exec(urlopen('https://bootstrap.pypa.io/ez_setup.py').read(), ez)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 452, in _open
    'unknown_open', req)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 1266, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>
```

**Comment by reinout** [comment]
That's probably the case if python has been build without ssl due to missing ssl libraries (probably you need to do `apt-get install libssl-dev`, or python2.7-dev might also be a good idea).

The core problem is that buildout needs a very very clean environment to run its tests in, mostly to test bootstrapping.

An alternative: run the tests with python 3.5, see if that compiles (or gives a better warning).

Another alternative: 

- just run the tests with your regular python

- ignore the test errors that have nothing to do with your code

- trust travis.ci to run the entire test suite in a clean environment

**Comment by mgedmin** [comment]
> probably you need to do apt-get install libssl-dev, or python2.7-dev might also be a good idea

Not on Mac OS X ;)

**Comment by gotcha** [comment]
I changed `Makefile` a lot for 3.0. And I work on MacOSX. Issue gone AFAIK.
