### ISSUE TITLE
zc.recipe.egg may fail with TypeError: can't pickle zipimport.zipimporter objects

### ISSUE THREAD

**Issue by datakurre** [buildout/buildout#478]
Because it relies on being able to deepcopy the current working set, and that is not possible if the working set includes zipped eggs raising exception `TypeError: can't pickle zipimport.zipimporter objects`.

I resolved this for myself with registering naive pickler for zipimporter objects

```python
import copyreg
import zipimport

copyreg.pickle(zipimport.zipimporter, lambda x: (x.__class__, (x.archive, )))
```

**Comment by gotcha** [comment]
@datakurre Is your fix stable enough that it deserves being added to `zc.buildout` ?

**Comment by datakurre** [comment]
@gotcha I don't know. It seems that I have not been needing that patch for some time. Originally I needed it with some Plone-related nix-shell based development environment where Nix Python environment provided zipped setuptools version.

I am ok also for just closing this, because it seems that almost nobody else has seen this.

**Comment by gotcha** [comment]
@Cykooz @eludum @encolpe Do you have a need for this ? An opinion on Asko's fix ?

**Comment by encolpe** [comment]
I'm using his fix as a patch since one year.

**Comment by datakurre** [comment]
Sounds like it is useful and robust then :)

**Comment by encolpe** [comment]
Yes, I owe you a beer.

**Comment by gotcha** [comment]
@encolpe How can I reproduce the issue ? In order to add a test...

**Comment by Cykooz** [comment]
I'm using other workaround. I hardcode in my `bootstrap.py` file a version of `setuptools` that less than version used by any my project. For example, `bootstrap.py` is installing version 39.0 (this version will be installed as zipped egg-file). After that `./bin/buildout` will upgrade `setuptools` to newer version. New version will be installed as unzipped egg.

If bootstarp's version is equal to buildout's version of `setuptools` then "can't pickle" error happen.

PS: Eggs-directory must not contain unzipped `setuptools` of required  version before `bootstrap.py` will run . Otherwise zip-version of egg will not be installed.

**Comment by gotcha** [comment]
@Cykooz iow, you only have the issue when using `bootstrap-buildout.py` ?

**Comment by Cykooz** [comment]
Yes, I have the issue only with `setuptools` installed by `bootstrap-buildout.py`.

**Comment by gotcha** [comment]
@encolpe Do you still need the patch ? If yes, in which circumstances ?

**Comment by encolpe** [comment]
@gotcha  I didn't read your last message.

Here it comes:

```
python3.7 -m venv /tmp/env --buildout-version=2.13.1--setuptools-version=40.8.0

mkdir /tmp/test
cd /tmp/test 
curl -O https://bootstrap.pypa.io/bootstrap-buildout.py
curl -O https://bootstrap.pypa.io/ez_setup.py

cat  << EOF > pinned.cfg 
[versions]
setuptools = 40.8.0
zc.buildout = 2.13.1
EOF

cat << EOF > buildout.cfg
[buildout]
extends = pinned.cfg
show-picked-versions = true
parts =  doc
eggs =  
    cookiecutter

[test]
recipe = zc.recipe.egg
eggs =
    future==0.17.1
    pytest

[doc]
recipe = zc.recipe.egg
eggs =
    sphinx
    sphinxcontrib-plantuml
EOF

/tmp/env/bin/python3.7 bootstrap-buildout.py --buildout-version=2.13.1--setuptools-version=40.8.0
bin/buildout
```

It seems relative to ez_setup.py when you run bootstrap-buildout.py with a too recent setuptools version but it crashes only when zc.recipe.egg is installed.

Full log:
```
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-40.8.0.zip
Extracting in /tmp/tmpa2fnb3j9
Now working in /tmp/tmpa2fnb3j9/setuptools-40.8.0
Building a Setuptools egg in /tmp/bootstrap-ukagm1lu
warning: no previously-included files found matching 'pyproject.toml'
/tmp/bootstrap-ukagm1lu/setuptools-40.8.0-py3.7.egg
Creating directory '/tmp/test/eggs'.
Creating directory '/tmp/test/bin'.
Creating directory '/tmp/test/parts'.
Creating directory '/tmp/test/develop-eggs'.
Generated script '/tmp/test/bin/buildout'.



Getting distribution for 'zc.recipe.egg==2.0.7'.
Got zc.recipe.egg 2.0.7.
Unused options for buildout: 'eggs'.
Installing doc.
Getting distribution for 'sphinx==2.2.0'.
Got Sphinx 2.2.0.
Getting distribution for 'sphinxcontrib-plantuml==0.17'.
warning: no files found matching 'README'
warning: no files found matching 'LICENSE'
warning: no files found matching 'CHANGES.*'
Got sphinxcontrib-plantuml 0.17.
Getting distribution for 'sphinxcontrib-serializinghtml==1.1.3'.
Got sphinxcontrib-serializinghtml 1.1.3.
Getting distribution for 'sphinxcontrib-qthelp==1.0.2'.
Got sphinxcontrib-qthelp 1.0.2.
Getting distribution for 'sphinxcontrib-jsmath==1.0.1'.
Got sphinxcontrib-jsmath 1.0.1.
Getting distribution for 'sphinxcontrib-htmlhelp==1.0.2'.
Got sphinxcontrib-htmlhelp 1.0.2.
Getting distribution for 'sphinxcontrib-devhelp==1.0.1'.
Got sphinxcontrib-devhelp 1.0.1.
Getting distribution for 'sphinxcontrib-applehelp==1.0.1'.
Got sphinxcontrib-applehelp 1.0.1.
Getting distribution for 'snowballstemmer==1.9.0'.
zip_safe flag not set; analyzing archive contents...
Got snowballstemmer 1.9.0.
Getting distribution for 'requests==2.22.0'.
Got requests 2.22.0.
Getting distribution for 'packaging==19.1'.
Got packaging 19.1.
Getting distribution for 'imagesize==1.1.0'.
Got imagesize 1.1.0.
Getting distribution for 'docutils==0.15.2'.
Got docutils 0.15.2.
Getting distribution for 'babel==2.7.0'.
Got Babel 2.7.0.
Getting distribution for 'alabaster==0.7.12'.
Got alabaster 0.7.12.
Getting distribution for 'Pygments==2.4.2'.
Got Pygments 2.4.2.
Getting distribution for 'Jinja2==2.10.1'.
Got Jinja2 2.10.1.
Getting distribution for 'urllib3==1.25.3'.
Got urllib3 1.25.3.
Getting distribution for 'idna==2.8'.
Got idna 2.8.
Getting distribution for 'chardet==3.0.4'.
Got chardet 3.0.4.
Getting distribution for 'certifi==2019.6.16'.
Got certifi 2019.6.16.
Getting distribution for 'six==1.12.0'.
Got six 1.12.0.
Getting distribution for 'pyparsing==2.4.2'.
Got pyparsing 2.4.2.
Getting distribution for 'attrs==19.1.0'.
Got attrs 19.1.0.
Getting distribution for 'pytz==2019.2'.
Got pytz 2019.2.
Getting distribution for 'MarkupSafe==1.1.1'.
Got MarkupSafe 1.1.1.
While:
  Installing doc.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/test/eggs/zc.buildout-2.13.1-py3.7.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/tmp/test/eggs/zc.buildout-2.13.1-py3.7.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/tmp/test/eggs/zc.buildout-2.13.1-py3.7.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/tmp/test/eggs/zc.recipe.egg-2.0.7-py3.7.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/tmp/test/eggs/zc.recipe.egg-2.0.7-py3.7.egg/zc/recipe/egg/egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "/tmp/test/eggs/zc.recipe.egg-2.0.7-py3.7.egg/zc/recipe/egg/egg.py", line 174, in _working_set
    return copy.deepcopy(cache_storage[cache_key])
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 221, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/lib/python3.7/copy.py", line 221, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle zipimport.zipimporter objects
```

**Comment by gotcha** [comment]
@encolpe Would you try with newest buildout 3.0.0bx ? It does work for me.

That is:

    virtualenv-3.7 tmp/env
    cd tmp/env
    bin/pip install zc.buildout==3.0.0b1
    bin/buildout

**Comment by encolpe** [comment]
Installing zc.buildout with pip works, with 3.0.0b1 and with 2.13.1.
Thanks
