### ISSUE TITLE
When used with Flask, how do I update templates?

### ISSUE THREAD

**Issue by nyck33** [buildout/buildout#530]
https://github.com/cyrilrbt/canadian-nutrient-file

is the repo I cloned.  I want to make changes to the templates but they are not reflected even upon restarting the server.  
```
├── base.cfg
├── bin
│   ├── buildout
│   ├── cnf
│   ├── pip
│   ├── pip3
│   ├── pip3.7
│   ├── python
│   └── wheel
├── bootstrap.py
├── buildout.cfg
├── canadian_nutrient_file.egg-info
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── not-zip-safe
│   ├── PKG-INFO
│   ├── requires.txt
│   ├── SOURCES.txt
│   └── top_level.txt
├── cnf
│   ├── __init__.py
│   ├── main.py
│   ├── models.py
│   ├── __pycache__
│   ├── scripts.py
│   ├── settings.py
│   ├── templates
│   └── views.py
├── cnf_csv
│   ├── CONVERSION FACTOR.csv
│   ├── FOOD GROUP.csv
│   ├── FOOD NAME.csv
│   ├── FOOD SOURCE.csv
│   ├── MEASURE NAME.csv
│   ├── NUTRIENT AMOUNT.csv
│   ├── NUTRIENT NAME.csv
│   ├── NUTRIENT SOURCE.csv
│   ├── REFUSE AMOUNT.csv
│   ├── REFUSE NAME.csv
│   ├── YIELD AMOUNT.csv
│   └── YIELD NAME.csv
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── develop-eggs
│   └── canadian-nutrient-file.egg-link
├── eggs
│   ├── coverage-4.4.1-py3.7.egg
│   ├── Flask-0.12.2-py3.7.egg
│   ├── flask_mongoengine-0.9.3-py3.7.egg
│   ├── Flask_Script-2.0.5-py3.7.egg
│   ├── Flask_Testing-0.6.2-py3.7.egg
│   ├── mongoengine-0.13.0-py3.7.egg
│   ├── nose-1.3.7-py3.7.egg
│   ├── pylint-1.7.0-py3.7.egg
│   ├── python_dateutil-2.6.1-py3.7.egg
│   ├── setuptools-33.1.1-py3.7.egg
│   ├── zc.buildout-2.13.3-py3.7.egg
│   └── zc.buildout-2.9.4-py3.7.egg
├── LICENSE
├── MANIFEST.in
├── parts
├── README.md
├── setup.cfg
├── setup.py
├── src
│   ├── pip-delete-this-directory.txt
│   └── webpy
└── versions.cfg
```
That is the project tree.  Is there a rebuild command after making changes to templates or any other code that needs to be run?
I have not changed the configuration from the default in the repo.  
```
import os
import datetime
from urllib.parse import urljoin


ROOT_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

DEBUG = (os.getenv('CNF_DEBUG', 'True') == 'True')
TESTING = (os.getenv('CNF_TESTING', 'True') == 'True')
FLASK_DEBUG = DEBUG
FLASK_BIND = os.getenv('CNF_BIND', 'localhost')
FLASK_PORT = int(os.getenv('CNF_PORT', 8888))
ROOT_URL = 'http://' + FLASK_BIND + ':' + str(FLASK_PORT) + '/'

TEMPLATE_FOLDER = os.path.join(ROOT_PATH, 'cnf', 'templates')

MONGODB_HOST = os.getenv('CNF_MONGO_HOST', 'localhost')
MONGODB_PORT = int(os.getenv('CNF_MONGO_PORT', 27017))
MONGODB_DB = os.getenv('CNF_MONGO_DB', 'cnf')
```

**Comment by icemac** [comment]
Making changes in the project code or the templates should not require a rebuild.
The only thing you can try – where `zc.buildout` is involved – is to run: `bin/buildout`

**Comment by nyck33** [comment]
```
(gamechangers) nobu@gold3forever:~/Desktop/canadian-nutrient-file-rev$ bin/buildout
Upgraded:
  zc.buildout version 2.9.4;
Restarting.
Develop: '/home/nobu/Desktop/canadian-nutrient-file-rev/.'
While:
  Installing.
  Getting section eggs.
  Initializing section eggs.
  Loading zc.buildout recipe entry zc.recipe.egg:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 2196, in main
    getattr(buildout, command)(args)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 710, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 710, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1343, in __getitem__
    options._initialize()
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1451, in _initialize
    self.initialize()
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1457, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1412, in _install_and_load
    req.project_name, group, entry)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2461, in load
    self.require(*args, **kwargs)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2484, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (zc.buildout 2.9.4 (/home/nobu/Desktop/canadian-nutrient-file-rev/eggs/zc.buildout-2.9.4-py3.7.egg), Requirement.parse('zc.buildout>=2.12.0'))
(gamechangers) nobu@gold3forever:~/Desktop/canadian-nutrient-file-rev$ zc.buildout --version
zc.buildout: command not found
```
The above error trace is what I get.

**Comment by mauritsvanrees** [comment]
From the traceback, buildout is trying to upgrade or downgrade itself to version 2.9.4, but some other package requires at least zc.buildout 2.12.0.
So as first step, edit the [versions file](https://github.com/cyrilrbt/canadian-nutrient-file/blob/master/versions.cfg#L21) and change the line to `zc.buildout = 2.12.0`. 
Or better use the most recent version: `zc.buildout = 2.13.3`. That version also has better error reporting when there is a version conflict.
Then run `bin/buildout` again.

**Comment by nyck33** [comment]
All went well until, 
```
Upgraded:
  zc.buildout version 2.13.3;
Restarting.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/buildout'.
Develop: '/home/nobu/Desktop/canadian-nutrient-file-rev/.'
Uninstalling eggs.
Installing eggs.
Getting distribution for 'mccabe==0.6.1'.
Got mccabe 0.6.1.
Getting distribution for 'astroid==1.5.3'.
Got astroid 1.5.3.
Getting distribution for 'six==1.10.0'.
Got six 1.10.0.
Getting distribution for 'isort==4.2.15'.
Got isort 4.2.15.
Getting distribution for 'editdistance==0.3.1'.
Got editdistance 0.3.1.
Getting distribution for 'wrapt==1.10.10'.
Got wrapt 1.10.10.
Getting distribution for 'lazy-object-proxy==1.3.1'.
Got lazy-object-proxy 1.3.1.
Getting distribution for 'Jinja2==2.9.6'.
Got Jinja2 2.9.6.
Getting distribution for 'click==6.7'.
Got click 6.7.
Getting distribution for 'itsdangerous==0.24'.
Got itsdangerous 0.24.
Getting distribution for 'Werkzeug==0.12.2'.
Got Werkzeug 0.12.2.
Getting distribution for 'pymongo==3.4.0'.
Got pymongo 3.4.0.
Getting distribution for 'Flask-WTF==0.14.2'.
Got Flask-WTF 0.14.2.
Getting distribution for 'MarkupSafe==1.0'.
    ERROR: Command errored out with exit status 1:
     command: /home/nobu/anaconda3/envs/gamechangers/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-l99szul4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-l99szul4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-l99szul4/pip-egg-info
         cwd: /tmp/pip-req-build-l99szul4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-l99szul4/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
No .dist-info directory after successful pip install of /tmp/tmplx11l3s8get_dist/MarkupSafe-1.0.tar.gz
While:
  Installing eggs.
  Getting distribution for 'MarkupSafe==1.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 2196, in main
    getattr(buildout, command)(args)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 826, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1622, in _call
    return f()
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/recipe/egg/egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/recipe/egg/egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/easy_install.py", line 962, in install
    return installer.install(specs, working_set)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/easy_install.py", line 735, in install
    for dist in self._get_dist(req, ws):
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/easy_install.py", line 579, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/easy_install.py", line 1888, in _move_to_eggs_dir_and_compile
    [tmp_loc] = call_pip_install(dist.location, tmp_dest)
  File "/home/nobu/anaconda3/envs/gamechangers/lib/python3.7/site-packages/zc/buildout/easy_install.py", line 1703, in call_pip_install
    ][0]
IndexError: list index out of range
```

**Comment by jamadden** [comment]
`Feature` was [removed from setuptools earlier this year](https://github.com/pypa/setuptools/issues/65). You'll either need an older setuptools, or a newer MarkupSafe. Newer versions of MarkupSafe distribute binary wheels so they're easier to install.

**Comment by nyck33** [comment]
```
Upgraded:
  zc.buildout version 2.13.3;
Restarting.
Develop: '/home/nobu/Desktop/canadian-nutrient-file-rev/.'
Installing eggs.
Getting distribution for 'WTForms==2.1'.
Got WTForms 2.1.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/cnf'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/nosetests'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/nosetests-3.7'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/coverage'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/coverage-3.7'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/coverage3'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/epylint'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/pylint'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/pyreverse'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/symilar'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/isort'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/flask'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/buildout'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/wheel'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/pip'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/pip3'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/pip3.7'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/f2py'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/f2py3'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/f2py3.7'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/cheroot'.
Generated script '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/chardetect'.
Generated interpreter '/home/nobu/Desktop/canadian-nutrient-file-rev/bin/python'.
```

**Comment by nyck33** [comment]
@jamadden @mauritsvanrees 
Thanks guys, it seems to rebuild now but the templates still stay the same: https://github.com/nyck33/eco_gamechanger/blob/master/cnf/templates/index.html.
What is weird is that views.py shows:
```
@app.route('/', methods=['GET'], endpoint='cnf.index')
def index():
    q = request.args.get('q')
    foods = CNFFoodName.objects.filter(description__icontains=q) if q else []
    return render_template('index.html', foods=foods, q=q)
```
But index.html looks different:
```
{% extends 'layout.html' %}
{% block content %}
<div class="container pt-4">
  <div class="row py-4">
    <div class="col text-center">
      <h1>Canadian Nutrient File Food Search</h1>
        <p>hello</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <form method='GET'>
        <input class="form-control" name="q" value="{{ q|default('', True) }}" />
      </form>
    </div>
    {% if foods %}
    <div class="col">
      <ul>
        {% for food in foods %}
        <li><a href="{{ url_for('cnf.show', food_id=food.id) }}">{{ food.description }}</a></li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}
```

I tried just inserting a simple `<p>hello</p>` near the top which does not appear.

**Comment by jamadden** [comment]
It’s not clear to me that this has anything to do with buildout anymore.  Buildout is an installer, not a web framework.

**Comment by nyck33** [comment]
That is true.
