### ISSUE TITLE
behaviour leaves buildout unusable and needing a re-bootstrap

### ISSUE THREAD

**Issue by cjw296** [buildout/buildout#54]
Here's the shell session:

buzzkill:checker chris$ bin/buildout -o
Develop: '/Users/chris/LocalGIT/checker/.'
Updating py.
While:
  Updating py.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/chris/buildout-eggs/zc.buildout-1.7.0-py2.7.egg/zc/buildout/buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "/Users/chris/buildout-eggs/zc.buildout-1.7.0-py2.7.egg/zc/buildout/buildout.py", line 595, in install
    installed_files = self[part]._call(update)
  File "/Users/chris/buildout-eggs/zc.buildout-1.7.0-py2.7.egg/zc/buildout/buildout.py", line 1345, in _call
    return f()
  File "/Users/chris/buildout-eggs/zc.recipe.egg-2.0.0a3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/Users/chris/buildout-eggs/zc.recipe.egg-2.0.0a3-py2.7.egg/zc/recipe/egg/egg.py", line 75, in working_set
    [options['develop-eggs-directory'], options['eggs-directory']]
TypeError: working_set() takes at least 3 arguments (2 given)

This leaves you with no buildout:

buzzkill:checker chris$ bin/buildout
-bash: bin/buildout: No such file or directory

**Comment by cjw296** [comment]
I'm pretty sure this can be closed, dunno if it's fixed anymore, but I don't use buildout anymore!
