### ISSUE TITLE
buildout version 3.0.0b1 is currently incompatible with batou.lib.buildout.Buildout

### ISSUE THREAD

**Issue by jugmac00** [buildout/buildout#558]
I wanted to be a good citizen, and try to update my Zope app to use the latest pre-release.

Currently, I do not know whether the problem is in `buildout` or `batou`, that is why I crossposted it in both issue trackers.
https://github.com/flyingcircusio/batou/issues/148

(batou is a deployment tool, which - in my case - executes buildout to deploy my Zope app).

With a minimal example of

```
from batou.component import Component
from batou.lib.buildout import Buildout


class Demo(Component):
    def configure(self):
        self += Buildout(python="3.8", setuptools="54.1.1", version="3.0.0b1")
```

I get the following problem...

```
./batou deploy dev
batou/2.2.4 (cpython 3.10.0-alpha6, Linux 5.4.0-66-generic x86_64)
====================================================== Preparing ======================================================
main: Loading environment `dev`...
main: Verifying repository ...
main: Loading secrets ...
=================================================== Connecting ... ====================================================
localhost: Connecting via local (1/1)
================================================ Configuring model ... ================================================
======================================== Waiting for remaining connections ... ========================================
====================================================== Deploying ======================================================
localhost: Scheduling component demo ...
localhost > Demo > Buildout > VirtualEnv('3.8') > Package('zc.buildout==3.0.0b1')
localhost > Demo > Buildout
ERROR: bin/buildout -t 3 -c "buildout.cfg"
Return code: 1
STDOUT

STDERR
Traceback (most recent call last):
  File "bin/buildout", line 5, in <module>
    from zc.buildout.buildout import main
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/buildout.py", line 18, in <module>
    import zc.buildout.easy_install
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 966, in <module>
    buildout_and_setuptools_dists = list(install(['zc.buildout'], None,
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 964, in install
    return installer.install(specs, working_set)
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 737, in install
    for dist in self._get_dist(req, ws):
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 554, in _get_dist
    raise zc.buildout.UserError(
zc.buildout.UserError: We don't have a distribution for wheel
and can't install one in offline (no-install) mode.



========================================== DEPLOYMENT FAILED (during deploy) ==========================================
```

**Comment by jugmac00** [comment]
See https://github.com/flyingcircusio/batou/issues/148 - `batou` does a `--no-deps` installation of `zc.buildout`, which results in the above `wheel` error.

**Comment by gotcha** [comment]
Reading  https://github.com/flyingcircusio/batou/issues/148 and batou code makes me believe the issue needs to be fixed in batou.

Reopen if I am wrong.
