### ISSUE TITLE
missing top_level.txt causes error in 3.0.0b3

### ISSUE THREAD

**Issue by goschtl** [buildout/buildout#582]
when i try to install orjson in an zc.recipe.egg i get the following error:

Getting distribution for 'orjson'.
While:
  Installing app.
  Getting distribution for 'orjson'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2222, in main
    getattr(buildout, command)(args)
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/buildout.py", line 834, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1630, in _call
    return f()
  File "/Users/ck/work/reha/tmp/project/p6/eggs/zc.recipe.egg-2.0.7-py3.8-macosx-11.5-x86_64.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/Users/ck/work/reha/tmp/project/p6/eggs/zc.recipe.egg-2.0.7-py3.8-macosx-11.5-x86_64.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/Users/ck/work/reha/tmp/project/p6/eggs/zc.recipe.egg-2.0.7-py3.8-macosx-11.5-x86_64.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 966, in install
    return installer.install(specs, working_set)
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 739, in install
    for dist in self._get_dist(req, ws):
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 582, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1895, in _move_to_eggs_dir_and_compile
    [tmp_loc] = call_pip_install(dist.location, tmp_dest)
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1710, in call_pip_install
    return make_egg_after_pip_install(dest, distinfo_dir)
  File "/Users/ck/work/reha/tmp/project/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1762, in make_egg_after_pip_install
    with open(os.path.join(egg_dir, new_distinfo_dir, 'top_level.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ck/work/reha/tmp/project/p6/eggs/tmpekyysdlf/orjson-3.6.4-py3.8-macosx-11.5-x86_64.egg/orjson-3.6.4-py3.8-macosx-11.5-x86_64.dist-info/top_level.txt'

I looked in the easy_install.py i can easy create a fix and ask if the top_level.txt file exists before open it.

I am not sure if it has any other consequences.

Christian

**Comment by gotcha** [comment]
Fixed and released in https://pypi.org/project/zc.buildout/3.0.0b4/

@goschtl Can you check please ?

**Comment by goschtl** [comment]
the problem is gone... thanks
