### ISSUE TITLE
Buildout 3: Cannot create egg if namespace __init__ is missing.

### ISSUE THREAD

**Issue by icemac** [buildout/buildout#589]
Trying to install `ruamel.yaml.clib` fails with a traceback – `zc.buildout` tries to create an egg from the sdist, while `pip` uses the wheel existing on PyPI.

* `zc.buildout` version: 3.0.0b4
  * also tested on b2 and b3: same behavior
  * but 2.13.6 is able to create the egg successfully (from sdist)
  * `pip` uses the wheel `ruamel.yaml.clib-0.2.6-cp39-cp39-macosx_10_9_x86_64.whl`
* Python version: 3.9 (does not seem to matter)
* `pip`version: 21.2.4 and 21.3.1
* OS version: MacOS 11.6.1

Minimum example `buildout.cfg`:

```ini
[buildout]
parts = test
eggs-directory = eggs

[test]
recipe = zc.recipe.egg
eggs =
    ruamel.yaml.clib
```

Example buildout run:

```
$ bin/buildout -vv
Using buildout.cfg and bin/buildout.
Installing 'zc.recipe.egg'.
Picked: zc.recipe.egg = 2.0.7

Configuration data:
[buildout]
abi-tag-eggs = true
allow-hosts = *
allow-picked-versions = true
allow-unknown-extras = false
bin-directory = /.../bin
develop-eggs-directory = /.../develop-eggs
directory = /...
download-cache = /.../cache
eggs-directory = /.../eggs/cp39
executable = /.../bin/python3.9
extends-cache = /.../cache/extends
find-links =
install-from-cache = false
installed = /.../.installed.cfg
log-format =
log-level = INFO
newest = false
offline = false
parts = test
parts-directory = /.../parts
prefer-final = true
python = buildout
show-picked-versions = false
socket-timeout =
update-versions-file =
use-dependency-links = false
verbosity = 20
versions = versions
[test]
_b = /.../bin
_d = /.../develop-eggs
_e = /.../eggs/cp39
bin-directory = /.../bin
develop-eggs-directory = /.../develop-eggs
eggs = ruamel.yaml.clib
eggs-directory = /.../eggs/cp39
recipe = zc.recipe.egg
[versions]
ruamel.yaml.clib =
zc.buildout = >=3.0.0b4
zc.recipe.egg = >=2.0.6

Installing test.
Installing 'ruamel.yaml.clib'.
We have no distributions for ruamel.yaml.clib that satisfies 'ruamel.yaml.clib'.
Getting distribution for 'ruamel.yaml.clib'.
Download cache has ruamel.yaml.clib 0.2.6 at: /.../cache/dist/ruamel.yaml.clib-0.2.6.tar.gz
Running pip install:
"/.../bin/python3.9" "-c" "import sys; sys.path[0:0] = []; from pip._internal.cli.main import main; sys.exit(main())" "install" "--no-deps" "-t" "/.../eggs/cp39/tmpen0ii57i" "-v" "/.../cache/dist/ruamel.yaml.clib-0.2.6.tar.gz"
path=[]

Using pip 21.2.4 from /.../lib/python3.9/site-packages/pip (python 3.9)
Looking in indexes: https://pypi.org/simple
Processing /.../cache/dist/ruamel.yaml.clib-0.2.6.tar.gz
    Running command python setup.py egg_info
    sys.argv ['/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-req-build-pnfpy4qd/setup.py', 'egg_info', '--egg-base', '/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e']
    test compiling /var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/tmp_ruamel_fp0jz2dv/test_ruamel_yaml.c -> test_ruamel_yaml OK
    running egg_info
    creating /private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info
    writing /private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info/dependency_links.txt
    writing namespace_packages to /private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info/namespace_packages.txt
    writing top-level names to /private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info/top_level.txt
    writing manifest file '/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info/SOURCES.txt'
    reading manifest file '/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file '/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-pip-egg-info-jjl2zv1e/ruamel.yaml.clib.egg-info/SOURCES.txt'
Building wheels for collected packages: ruamel.yaml.clib
  Running command /.../bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-req-build-pnfpy4qd/setup.py'"'"'; __file__='"'"'/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-req-build-pnfpy4qd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-wheel-mbrg5jbd
  sys.argv ['/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-req-build-pnfpy4qd/setup.py', 'bdist_wheel', '-d', '/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-wheel-mbrg5jbd']
  test compiling /var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/tmp_ruamel_6510zxpa/test_ruamel_yaml.c -> test_ruamel_yaml OK
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.0-x86_64-3.9
  creating build/lib.macosx-11.0-x86_64-3.9/ruamel
  copying .ruamel/__init__.py -> build/lib.macosx-11.0-x86_64-3.9/ruamel
  creating build/lib.macosx-11.0-x86_64-3.9/ruamel/yaml
  copying .ruamel/yaml/__init__.py -> build/lib.macosx-11.0-x86_64-3.9/ruamel/yaml
  creating build/lib.macosx-11.0-x86_64-3.9/ruamel/yaml/clib
  copying ./__init__.py -> build/lib.macosx-11.0-x86_64-3.9/ruamel/yaml/clib
  copying ./LICENSE -> build/lib.macosx-11.0-x86_64-3.9/ruamel/yaml/clib
  running build_ext
  building '_ruamel_yaml' extension
  creating build/temp.macosx-11.0-x86_64-3.9
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c _ruamel_yaml.c -o build/temp.macosx-11.0-x86_64-3.9/_ruamel_yaml.o
  In file included from _ruamel_yaml.c:610:
  ./_ruamel_yaml.h:10:9: warning: 'PyString_CheckExact' macro redefined [-Wmacro-redefined]
  #define PyString_CheckExact PyBytes_CheckExact
          ^
  [... 49 other warnings]

  50 warnings generated.
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c api.c -o build/temp.macosx-11.0-x86_64-3.9/api.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c dumper.c -o build/temp.macosx-11.0-x86_64-3.9/dumper.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c emitter.c -o build/temp.macosx-11.0-x86_64-3.9/emitter.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c loader.c -o build/temp.macosx-11.0-x86_64-3.9/loader.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c parser.c -o build/temp.macosx-11.0-x86_64-3.9/parser.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c reader.c -o build/temp.macosx-11.0-x86_64-3.9/reader.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c scanner.c -o build/temp.macosx-11.0-x86_64-3.9/scanner.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/.../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c writer.c -o build/temp.macosx-11.0-x86_64-3.9/writer.o
  /usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk build/temp.macosx-11.0-x86_64-3.9/_ruamel_yaml.o build/temp.macosx-11.0-x86_64-3.9/api.o build/temp.macosx-11.0-x86_64-3.9/dumper.o build/temp.macosx-11.0-x86_64-3.9/emitter.o build/temp.macosx-11.0-x86_64-3.9/loader.o build/temp.macosx-11.0-x86_64-3.9/parser.o build/temp.macosx-11.0-x86_64-3.9/reader.o build/temp.macosx-11.0-x86_64-3.9/scanner.o build/temp.macosx-11.0-x86_64-3.9/writer.o -o build/lib.macosx-11.0-x86_64-3.9/_ruamel_yaml.cpython-39-darwin.so
  installing to build/bdist.macosx-11.0-x86_64/wheel
  running install
  running install_lib
  copying _ruamel_yaml.cpython-39-darwin.so -> build/bdist.macosx-11.0-x86_64/wheel
  Skipping installation of build/bdist.macosx-11.0-x86_64/wheel/ruamel/__init__.py (namespace package)
  Skipping installation of build/bdist.macosx-11.0-x86_64/wheel/ruamel/yaml/__init__.py (namespace package)
  copying ruamel/yaml/clib/LICENSE -> build/bdist.macosx-11.0-x86_64/wheel/ruamel/yaml/clib
  copying ruamel/yaml/clib/__init__.py -> build/bdist.macosx-11.0-x86_64/wheel/ruamel/yaml/clib
  running install_egg_info
  running egg_info
  writing ruamel.yaml.clib.egg-info/PKG-INFO
  writing dependency_links to ruamel.yaml.clib.egg-info/dependency_links.txt
  writing namespace_packages to ruamel.yaml.clib.egg-info/namespace_packages.txt
  writing top-level names to ruamel.yaml.clib.egg-info/top_level.txt
  reading manifest file 'ruamel.yaml.clib.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'ruamel.yaml.clib.egg-info/SOURCES.txt'
  Copying ruamel.yaml.clib.egg-info to build/bdist.macosx-11.0-x86_64/wheel/ruamel.yaml.clib-0.2.6-py3.9.egg-info
  running install_scripts
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  creating build/bdist.macosx-11.0-x86_64/wheel/ruamel.yaml.clib-0.2.6.dist-info/WHEEL
  creating '/private/var/folders/dn/l6fksjj91v78hz2503q68vr40000h1/T/pip-wheel-mbrg5jbd/ruamel.yaml.clib-0.2.6-cp39-cp39-macosx_11_0_x86_64.whl' and adding 'build/bdist.macosx-11.0-x86_64/wheel' to it
  adding '_ruamel_yaml.cpython-39-darwin.so'
  adding 'ruamel.yaml.clib-0.2.6.dist-info/LICENSE'
  adding 'ruamel.yaml.clib-0.2.6.dist-info/METADATA'
  adding 'ruamel.yaml.clib-0.2.6.dist-info/WHEEL'
  adding 'ruamel.yaml.clib-0.2.6.dist-info/namespace_packages.txt'
  adding 'ruamel.yaml.clib-0.2.6.dist-info/top_level.txt'
  adding 'ruamel.yaml.clib-0.2.6.dist-info/RECORD'
  removing build/bdist.macosx-11.0-x86_64/wheel
  Building wheel for ruamel.yaml.clib (setup.py) ... done
  Created wheel for ruamel.yaml.clib: filename=ruamel.yaml.clib-0.2.6-cp39-cp39-macosx_11_0_x86_64.whl size=137263 sha256=89f6e933fed665832496c1ae7ede67aaa70946ba2a2b8610651590346862e94b
  Stored in directory: /.../Library/Caches/pip/wheels/30/4a/dd/685067b960ef0755b206bdda905ea4f2ef0152f6479fd36860
Successfully built ruamel.yaml.clib
Installing collected packages: ruamel.yaml.clib
Successfully installed ruamel.yaml.clib-0.2.6
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/.../bin/python3.9 -m pip install --upgrade pip' command.
While:
  Installing test.
  Getting distribution for 'ruamel.yaml.clib'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/.../lib/python3.9/site-packages/zc/buildout/buildout.py", line 2237, in main
    getattr(buildout, command)(args)
  File "/.../lib/python3.9/site-packages/zc/buildout/buildout.py", line 842, in install
    installed_files = self[part]._call(recipe.install)
  File "/.../lib/python3.9/site-packages/zc/buildout/buildout.py", line 1638, in _call
    return f()
  File "/.../eggs/cp39/zc.recipe.egg-2.0.7-py3.9-macosx-11.6-x86_64.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/.../eggs/cp39/zc.recipe.egg-2.0.7-py3.9-macosx-11.6-x86_64.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/.../eggs/cp39/zc.recipe.egg-2.0.7-py3.9-macosx-11.6-x86_64.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/.../lib/python3.9/site-packages/zc/buildout/easy_install.py", line 966, in install
    return installer.install(specs, working_set)
  File "/.../lib/python3.9/site-packages/zc/buildout/easy_install.py", line 691, in install
    for dist in self._get_dist(requirement, ws):
  File "/.../lib/python3.9/site-packages/zc/buildout/easy_install.py", line 582, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/.../lib/python3.9/site-packages/zc/buildout/easy_install.py", line 1904, in _move_to_eggs_dir_and_compile
    [tmp_loc] = call_pip_install(dist.location, tmp_dest)
  File "/.../lib/python3.9/site-packages/zc/buildout/easy_install.py", line 1710, in call_pip_install
    return make_egg_after_pip_install(dest, distinfo_dir)
  File "/.../lib/python3.9/site-packages/zc/buildout/easy_install.py", line 1732, in make_egg_after_pip_install
    with open(init_py_file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/.../eggs/cp39/tmpen0ii57i/ruamel/__init__.py'
```

**Comment by gotcha** [comment]
Should be fixed in https://pypi.org/project/zc.buildout/3.0.0b5/

@icemac  Can you check ?

**Comment by icemac** [comment]
@gotcha It worked, thank you for fixing this issue.
