### ISSUE TITLE
zc.buildout 3.0.0 broken

### ISSUE THREAD

**Issue by dataflake** [buildout/buildout#625]
In a buildout that ran just fine yesterday with zc.buildout version 3.0.0rc3 I am now seeing the following traceback after updating to zc.buildout version 3.0.0. Nothing else has changed.

```
$ bin/buildout
While:
  Initializing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/jens/src/venv/lib/python3.8/site-packages/zc/buildout/configparser.py", line 194, in parse
    marker = packaging.markers.Marker(expr)
AttributeError: module 'packaging' has no attribute 'markers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jens/src/venv/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2250, in main
    buildout = Buildout(config_file, options,
  File "/Users/jens/src/venv/lib/python3.8/site-packages/zc/buildout/buildout.py", line 383, in __init__
    cfg_data, _ = _open(
  File "/Users/jens/src/venv/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1884, in _open
    eresult, user_defaults = _open(
  File "/Users/jens/src/venv/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1861, in _open
    result = zc.buildout.configparser.parse(
  File "/Users/jens/src/venv/lib/python3.8/site-packages/zc/buildout/configparser.py", line 196, in parse
    except packaging.markers.InvalidMarker:
AttributeError: module 'packaging' has no attribute 'markers'
```

I have tried updating `packaging` to the latest release (21.3), doesn't help. There's a weird import issue going on:

```
$ bin/python
Python 3.8.15 (default, Nov  1 2022, 07:26:00)
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import packaging
>>> packaging.markers.InvalidMarker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'packaging' has no attribute 'markers'
>>> from packaging import markers
>>> markers.InvalidMarker
<class 'packaging.markers.InvalidMarker'>
```

**Comment by leorochael** [comment]
This seems to be fixed by #624

**Comment by leorochael** [comment]
`packaging.markers`, being a subpackage, is not necessarily automatically imported when importing `packaging`.

Another fix would be to `import  packaging.markers` instead of `import packaging`.
