### ISSUE TITLE
Fail to install when trying to use package with pyproject.toml in develop

### ISSUE THREAD

**Issue by tyctor** [buildout/buildout#645]
Hi

when i want to use package in [develop](https://www.buildout.org/en/latest/getting-started.html#python-development-projects)
and package have only `pyproject.toml` (no `setup.py`)
installation fails

```
Develop: '/home/tyctor/projects/punctum.cz/src/django-tinymce'
Traceback (most recent call last):
  File "/tmp/tmpac98s9w_", line 13, in <module>
    with open('/home/tyctor/projects/punctum.cz/src/django-tinymce/setup.py') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tyctor/projects/punctum.cz/src/django-tinymce/setup.py'
While:
  Installing.
  Processing develop directory '/home/tyctor/projects/punctum.cz/src/django-tinymce'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/tyctor/projects/punctum.cz/lib/python3.9/site-packages/zc/buildout/buildout.py", line 2252, in main
    getattr(buildout, command)(args)
  File "/home/tyctor/projects/punctum.cz/lib/python3.9/site-packages/zc/buildout/buildout.py", line 718, in install
    installed_develop_eggs = self._develop()
  File "/home/tyctor/projects/punctum.cz/lib/python3.9/site-packages/zc/buildout/buildout.py", line 961, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/tyctor/projects/punctum.cz/lib/python3.9/site-packages/zc/buildout/easy_install.py", line 1120, in develop
    call_subprocess(args)
  File "/home/tyctor/projects/punctum.cz/lib/python3.9/site-packages/zc/buildout/easy_install.py", line 172, in call_subprocess
    raise Exception(
Exception: Failed to run command:
'/home/tyctor/projects/punctum.cz/bin/python3.9', '/tmp/tmpac98s9w_', '-q', 'develop', '-mN', '-d', '/home/tyctor/projects/punctum.cz/develop-eggs/tmpufy542nabuild'
```

**Comment by icemac** [comment]
Currently `buildout` only supports packages which have a `setup.py`.
