### ISSUE TITLE
Python 3.13 support: no module named 'distutils'

### ISSUE THREAD

**Issue by elikoga** [buildout/buildout#650]
This line https://github.com/buildout/buildout/blob/a8d182c25d3ff18197af3531fcf8c827b85eddbd/src/zc/buildout/buildout.py#L35

And a few other mentions of `distutils` make buildout currently incompatible with python 3.12, where `distutils` has been deprecated.

**Comment by mauritsvanrees** [comment]
The import works fine for me on Python 3.12.  Do you mean 3.13 instead?

```
$ python3.12
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
fancycompleter not found
>>> import distutils.errors
```

**Comment by mauritsvanrees** [comment]
I now have Python 3.13 installed, and indeed it fails:

```
$ python3.13
Python 3.13.0b2 (main, Jun 16 2024, 13:17:34) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
fancycompleter not found
>>> import distutils.errors
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import distutils.errors
ModuleNotFoundError: No module named 'distutils'
```

I will update the title of this issue.

**Comment by mauritsvanrees** [comment]
Python 3.13 is supported since release 4.0.0a1.  A final (non-alpha) release is expected soon, probably today.

**Comment by Kaki-In** [comment]
Hello, 

```
$ python3.13 -m pip
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3/dist-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils'

$ python3.13 -m pip install setuptools
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3/dist-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils'

$ sudo apt install python3-setuptools
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
python3-setuptools est déjà la version la plus récente (59.6.0-1.2ubuntu0.22.04.3).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 85 non mis à jour.
```

How do you fix this ??

**Comment by mauritsvanrees** [comment]
See the comment above: `pip install setuptools`.  `setuptools` has a copy of `distutils` included.

Let me try it out for good measure:

```
$ python3.13 -m venv foo
$ cd foo
$ . bin/activate
$ python
>>> import distutils
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import distutils
ModuleNotFoundError: No module named 'distutils'
$ pip install setuptools
$ python
>>> import distutils
>>> distutils
<module 'distutils' (/Users/maurits/tmp/foo/lib/python3.13/site-packages/setuptools/_distutils/__init__.py)>
```

**Comment by mauritsvanrees** [comment]
@Kaki-In Sorry, I did not read your comment carefully, so my comment may not help.  But still, first creating a virtual environment with `python3.13 -m venv` may help.

Otherwise it may help to know which Linux version you are using and how you installed Python 3.13.  But from what you post, it does not look like you are doing anything with `zc.buildout`, so might be something to ask on StackOverflow.

**Comment by Kaki-In** [comment]
@mauritsvanrees Thanks for your answer. I tried creating a virtual environment and it's finally working perfectly using this !

**Comment by Kaki-In** [comment]
Just got this other error while installing a packet using `pip` in my environment : 

```
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<path>/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "<path>/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<path>/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-x4hjehpr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-x4hjehpr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-x4hjehpr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-x4hjehpr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      ModuleNotFoundError: No module named 'pkg_resources'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Any idea on how to fix this ?

**Comment by mauritsvanrees** [comment]
> ModuleNotFoundError: No module named 'pkg_resources'

Starting with `setuptools` 82 the `pkg_resources` module is gone.  I don't know which package you are trying to install, but most likely it uses `pkg_resources` style namespaces, instead of native namespaces.

Best would be if that package can switch to native namespaces.
Some background info is here: https://6.docs.plone.org/developer-guide/native-namespace.html

But easiest is to make sure you are using an older setuptools version.

```
python3.12 -mvenv tmp
cd tmp
. bin/activate
pip install 'setuptools<82'
pip install --no-build-isolation ... (whatever package you tried to install)
```

The `--no-build-isolation` option means that the setuptools version that is installed in your virtual environment will be used.  Without build isolation, pip will look in the `pyproject.toml` of the package you try to install, look for a `build-system` setting there, and likely will use the most recent `setuptools` version.

If you yourself are the writer of the package, you could add or edit a `pyproject.toml` in it, with as minimum something like this:

```
[build-system]
requires = ["setuptools<82"]
```
