### ISSUE TITLE
Cannot develop pyproject.toml only packages

### ISSUE THREAD

**Issue by mauritsvanrees** [buildout/buildout#652]
I am working on a package that has only a `pyproject.toml` and no `setup.py`.  This does not work with Buildout when you have it in develop mode:

```
Develop: '/Users/maurits/community/plone-coredev/6.1/plips/../src/plone.classicui'
Traceback (most recent call last):
  File "/var/folders/26/1plvhxbs6yx7g_82v2xdxc500000gn/T/tmphrtknwp2", line 13, in <module>
    with open('/Users/maurits/community/plone-coredev/6.1/plips/../src/plone.classicui/setup.py') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maurits/community/plone-coredev/6.1/plips/../src/plone.classicui/setup.py'
While:
  Installing.
  Processing develop directory '/Users/maurits/community/plone-coredev/6.1/plips/../src/plone.classicui'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.1/lib/python3.12/site-packages/zc/buildout/buildout.py", line 2252, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/community/plone-coredev/6.1/lib/python3.12/site-packages/zc/buildout/buildout.py", line 718, in install
    installed_develop_eggs = self._develop()
                             ^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.1/lib/python3.12/site-packages/zc/buildout/buildout.py", line 961, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/Users/maurits/community/plone-coredev/6.1/lib/python3.12/site-packages/zc/buildout/easy_install.py", line 1120, in develop
    call_subprocess(args)
  File "/Users/maurits/community/plone-coredev/6.1/lib/python3.12/site-packages/zc/buildout/easy_install.py", line 172, in call_subprocess
    raise Exception(
Exception: Failed to run command:
'/Users/maurits/community/plone-coredev/6.1/bin/python3.12', '/var/folders/26/1plvhxbs6yx7g_82v2xdxc500000gn/T/tmphrtknwp2', '-q', 'develop', '-mN', '-d', '/Users/maurits/community/plone-coredev/6.1/develop-eggs/tmpzx7fbgfqbuild'
```

**Comment by davisagli** [comment]
I suspect buildout needs to gain some support for multiple PEP 660-compatible build tools (see https://stackoverflow.com/a/69711730) rather than assuming it can run `setup.py develop`.
