### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by mgedmin** [buildout/buildout#99]
When you try to use fancy version constraints like `foo = < 4.0dev` in your `buildout.cfg`, and you accidentally run the 1.7 bootstrap, instead of a clear error message saying this feauture is unsupported you get this internal error:
```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\buildout.py", line 625, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\buildout.py", line 1345, in _call
    return f()
  File "build\bdist.win32\egg\zc\recipe\testrunner\__init__.py", line 46, in install
    eggs, ws = self._delegated.working_set(('zope.testrunner', ))
  File "c:\eggs\zc.recipe.egg-1.3.2-py2.6.egg\zc\recipe\egg\egg.py", line 101, in working_set
    **kw)
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\easy_install.py", line 1079, in install
    return installer.install(specs, working_set)
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\easy_install.py", line 905, in install
    req = self._constrain(requirements.pop(0))
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\easy_install.py", line 861, in _constrain
    requirement = _constrained_requirement(constraint, requirement)
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\easy_install.py", line 1910, in _constrained_requirement
    _constrained_requirement_constraint(constraint, requirement)
  File "c:\eggs\zc.buildout-1.7.1-py2.6.egg\zc\buildout\easy_install.py", line 1959, in _constrained_requirement_constraint
    cop, cv = _parse_constraint(constraint).group(1, 2)
AttributeError: 'NoneType' object has no attribute 'group'
```

(See [this failed build](http://winbot.zope.org/builders/zope.app.http_py_265_32/builds/796/steps/buildout/logs/stdio) for a live example)

**Comment by idgserpro** [comment]
Indeed this happens when using 1.7.1 and *fancy* version constraints (in our case it happened in a Linux machine), but this is solved in more "recent" versions like 2.2.5 (the one I tested). Wouldn't it be the case to just close this issue? If someone tries to google `AttributeError: 'NoneType' object has no attribute 'group'` will come here anyways and see this message.

**Comment by idgserpro** [comment]
Doing `foo = >4.0dev` instead of `foo = > 4.0dev` (this second one have a whitespace after `>`) works as well. Didn't check why tough.

**Comment by jimfulton** [comment]
This isn't a bug in buildout2 and no one should be using buildout 2. Closing as @idgserpro suggested.

**Comment by mauritsvanrees** [comment]
> ... and no one should be using buildout 2.

You mean: no one should be using buildout 1, right?

BTW, 1.x is still working fine for me for sites that I only do bug fixes for. When I do bigger upgrades I definitely update to a recent zc.buildout and setuptools.

**Comment by idgserpro** [comment]
@mauritsvanrees the buildout used by Plone 4.3 should not be upgraded to the buildout 2? Today it uses the [1.7.1](https://github.com/plone/buildout.coredev/blob/4.3/versions.cfg#L2).

**Comment by mauritsvanrees** [comment]
@idgserpro We decided to stick to 1.7.1 for the Plone 4.3 series because there are too many possible corner cases where updating zc.buildout and setuptools and bootstrap.py does not always work, especially on older servers. No real technical reason: newer buildouts will work fine. You can open an issue in https://github.com/plone/Products.CMFPlone/issues when you want to discuss this.
